### ISSUE TITLE
Evaluate for release

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino-pretty#1]
@pinojs/pino please evaluate this codebase for release readiness. I'd like at least @mcollina and @davidmarkclements to sign off before I publish it.

@hbarcelos please verify that error stack traces are formatted correctly.

@ilyaztsv please verify that it properly supports defining which properties of an error object to display.

@victor0801x please verify that it outputs localized times as desired.

**Comment by ilyaztsv** [comment]
Hi @jsumners !

I've checked `errorProps` flag and it works as expected.

But one thing, if I use the the flag without arguments (`pino-pretty --errorProps`) there is no error.
`Pino` provides the following error `errorProps flag provided without a string argument` in this case.

**Comment by ilyaztsv** [comment]
Also one thing, related to https://github.com/pinojs/pino/issues/382
Here we still have the same issue. May be need to fix it after merging https://github.com/pinojs/pino/pull/383

**Comment by jsumners** [comment]
@davidmarkclements:
+ Weird. I do not have any failing tests over here and I have the same environment. But this comment did make me realize the `--color` option would not pass in correctly. I have updated that to `--colorize`.
+ The idea is that `pino` will not ship with a prettifier. Instead, it will advertise those that exist. The constant need for more and more options to the prettifier, and the resulting dependency needs, are exactly the reason for it. Currently, the heaviest dependencies come from having to deal with locale data regarding date/time formatting. The way this is done in `pino`, at the moment, is way too fragile and non-standard (how do the format strings even work in that implementation?).

@ilyaztsv the exact same solution proposed in `pino` issue 383 is used here : https://github.com/pinojs/pino-pretty/blob/4e337de675f2984bb15cbac9d5742bd30518d61a/index.js#L215

Where are you seeing the `null` stack problem?

Hmm, I suppose it wouldn't be too difficult to add in an error if the the `--errorProps` flag is supplied and set to default.

**Comment by jsumners** [comment]
@davidmarkclements try the tests again. I pushed some fixes.

**Comment by davidmarkclements** [comment]
@jsumners 

* test now passing
* ok so it doesn't come bundled. 🔝💯

**Comment by davidmarkclements** [comment]
LGTM - @mcollina over to you.

**Comment by hbarcelos** [comment]
## Error stacktraces

LGTM.

---

## Formatting

Output on current prettifier on monorepo:
```
[2018-04-02T17:52:21.736Z] INFO (12446 on henrique-7650): Application is listening on http://localhost:8888
```

Output using this repo using `-c -t`:
```
[2018-04-02 18:03:48.220 +0000] INFO (18261 on henrique-7650): Application is listening on http://localhost:8888
```

### Screenshots

From monorepo:
![before](https://user-images.githubusercontent.com/16565602/38208563-dd4acfec-3687-11e8-8b2c-89d5e4a2c197.png)

From this repo:
![after](https://user-images.githubusercontent.com/16565602/38208585-ecc74964-3687-11e8-8ae4-9041f4b613f2.png)

I'm not sure about that `+0000`, I'd rather have the date formatted as ISO 8601 "cannonical" form. What do you think about this, guys?

Also, the message is not colorized anymore, even with the `-c` option. I used to like it, but this is only my personal opinion.

**Comment by jsumners** [comment]
@hbarcelos the date time format is customizable.

The message not being highlighted sounds like a bug.

**Comment by hbarcelos** [comment]
@jsumners I see. However, I believe the default format should remain the same as the one from the monorepo, because most people are probably used to it and we shouldn't disrupt the user experience unless there's a good reason to do so.

Regarding the message highlighting, I'm running `pino@4.15.0`. I cloned this repo and ran `npm link` to make it available locally. Finally, in the app that uses `pino`, I ran:

```
yarn run dev:start | yarn run pino-pretty -t -c
```

Can anyone reproduce this?

**Comment by jsumners** [comment]
@hbarcelos I need to add a color function wrapper call here https://github.com/pinojs/pino-pretty/blob/c67350aa184fe7345cd848bdf70bce6591c8e24e/index.js#L137

**Comment by jsumners** [comment]
The message should now be colored correctly.

**Comment by ilyaztsv** [comment]
@jsumners thanks for the reply!

Log example:

```
{"level":50,"time":1457537229339,"msg":"Error message.","pid":44127,"hostname":"MacBook-Pro-3.home","type":"Error","stack":"Stack of the error","statusCode":500,"dataBaseSpecificError":{"errorType":"some database error type","erroMessage":"some database error message","evenMoreSpecificStuff":{"someErrorRelatedObject":"error"}},"v":1}
```

Result of `cat log.log | pino-pretty --errorProps '*'`:

```
[1457537229339] ERROR (44127 on MacBook-Pro-3.home): Error message.
    Stack of the error
statusCode: 500
dataBaseSpecificError: {
    errorType: "some database error type"
    erroMessage: "some database error message"
    evenMoreSpecificStuff: {
      "someErrorRelatedObject": "error"
    }
}
```

Result of `cat log.log | pino-pretty --errorProps statusCode`:

```
[1457537229339] ERROR (44127 on MacBook-Pro-3.home): Error message.
    Stack of the error
statusCode: 500
```

Screenshots:

<img width="552" alt="screen shot 2018-04-03 at 15 02 38" src="https://user-images.githubusercontent.com/3539802/38236992-1724907c-3750-11e8-9e39-e7a695bd60f7.png">

<img width="561" alt="screen shot 2018-04-03 at 15 02 59" src="https://user-images.githubusercontent.com/3539802/38237011-22382276-3750-11e8-9420-b8b4cc0b922c.png">


About `null` stack problem:

if I have the following log file (where `"stack":null):

```
{"level":50,"time":1457537229339,"msg":"Error message.","pid":44127,"hostname":"MacBook-Pro-3.home","type":"Error","stack":null,"statusCode":500,"dataBaseSpecificError":{"errorType":"some database error type","erroMessage":"some database error message","evenMoreSpecificStuff":{"someErrorRelatedObject":"error"}},"v":1}
``

I get the following error:

```
/Users/ilyaztsv/projects/my/pino-pretty/index.js:180
      const lines = value.split(/\r?\n/)
                          ^

TypeError: Cannot read property 'split' of null
    at joinLinesWithIndentation (/Users/ilyaztsv/projects/my/pino-pretty/index.js:180:27)
    at pretty (/Users/ilyaztsv/projects/my/pino-pretty/index.js:145:23)
    at DestroyableTransform._transform (/Users/ilyaztsv/projects/my/pino-pretty/bin.js:30:24)
```

Probably, we need to add a condition before https://github.com/pinojs/pino-pretty/blob/8e03060ca0742b7eeacfb88a5951f4b695de125d/index.js#L145

Will you fix it or do I send PR?

**Comment by victor0801x** [comment]
@jsumners wonderful job.

I got this cross-date error.
![2018-04-03 18-17-01](https://user-images.githubusercontent.com/4534038/38243810-4674a7e8-376b-11e8-8201-5396e45cce21.png)

**Comment by mcollina** [comment]
Some notes:

1. it needs pictures (for the colors support) in the README
2. we should add support for the meta protocol, so that we are not parsing JSON if we are used within the same process.
3. are we planning on embedding this in pino@4, right? If so, embedding executables is tricky, you should make a `start()` function in `bin.js` and export that.

**Comment by jsumners** [comment]
@ilyaztsv a PR would be fantastic. Thank you.

@victor0801x interesting. Do you have any suggestions for fixing that test?

@mcollina we are **not** planning on embedding this in pino@4. I see this as our chance to issue pino@5. However, to retain *some* basic development environment capability I am planning to add a basic formatter for the `pino({prettyPrint: true})` scenario. I intend for this prettifier to only do the following: show the log level name, separate the epoch like `[123456]`, present the message, and list remaining properties in a readable manner.

**Comment by mcollina** [comment]
@jsumners I would prefer that if `{ prettyPrint: true }` is passed in, we dynamically do `require('pino-pretty')` and throw a nice error if that is missing.

**Comment by jsumners** [comment]
@mcollina that'd work too. I'll implement it that way.

FYI: I have already pegged a branch on `pinojs/pino` for "next-major".

**Comment by victor0801x** [comment]
@jsumners I'm still looking for better check
in pino's pretty.test.js (https://github.com/pinojs/pino/blob/master/test/pretty.test.js#L470:1), 
I pass the epoch time as msg, then check 
`
Date.parse('2018-03-31 01:35:28.992 +0800') === parseInt(msg, 10) // 1522431328992
`

**Comment by jsumners** [comment]
@victor0801x the issue is that this is a hard coded string:

https://github.com/pinojs/pino-pretty/blob/8e03060ca0742b7eeacfb88a5951f4b695de125d/test/basic.test.js#L140

What needs to be done to account for the test running in your timezone is to independently calculate the expected time from the `epoch` variable and substitute it into the expected string.

**Comment by victor0801x** [comment]
@jsumners can separately test local iso time & reuse or directly use joda covert into localiso ?
```js
const formatted = pretty(chunk.toString())
/*
const localISO = formatted.slice(formatted.indexOf('[') + 1, formatted.indexOf(']'))
*/
const zonedDateTime = joda.ZonedDateTime.ofInstant(
  joda.Instant.ofEpochMilli(epoch),
  joda.ZoneOffset.SYSTEM
)
const localISO = joda.DateTimeFormatter.ofPattern('yyyy-MM-dd HH:mm:ss.SSS Z').format(
  zonedDateTime
)

// make sure convert into localiso is correct
t.equal(Date.parse(localISO), epoch)

// make sure other properties are correct too
t.is(
  formatted,
  `[${localISO}] INFO (${pid} on ${hostname}): ${epoch}\n`
)

log.info(epoch)   
```

**Comment by jsumners** [comment]
@victor0801x I can accept that.

**Comment by jsumners** [comment]
@mcollina metadata API support is implemented https://github.com/pinojs/pino-pretty/commit/23db10a7b6c3d5316cc89128aefb8d408f23ef02

**Comment by jsumners** [comment]
And a picture in the readme https://github.com/pinojs/pino-pretty/commit/1a072501fba8317d572d8fbdfb7d963e9644a748

**Comment by mcollina** [comment]
Currently this module installs the full webpack and preforms a build upon install. Not sure why, but I'm very 👎 on that approach:

```
$ npm i
npm WARN deprecated npmconf@2.0.9: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
WARN tar stripping C:/ from absolute pathl extract hawk@3.1.3

> cldr-data@32.0.1 install /Users/matteo/Repositories/pino-pretty/node_modules/cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/32.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/32.0.0.zip`
  [========================================] 31967630/31967630 100% 0.0s
Received 31218K total.
Unpacking it into `./`

> pre-commit@1.2.2 install /Users/matteo/Repositories/pino-pretty/node_modules/pre-commit
> node install.js


> spawn-sync@1.0.15 postinstall /Users/matteo/Repositories/pino-pretty/node_modules/spawn-sync
> node postinstall


> js-joda-locale@1.0.0 postinstall /Users/matteo/Repositories/pino-pretty/node_modules/js-joda-locale
> POSTINSTALL_BUILD=1 postinstall-build __always_build__ --only-as-dependency --script build_package

postinstall-build:
  This version of npm (5.8.0) may not be compatible with postinstall-build! There
  are outstanding bugs in certain versions of npm that prevent it from working with
  postinstall-build. See https://github.com/exogen/postinstall-build#bugs-in-npm
  for more information.


> fsevents@1.1.3 install /Users/matteo/Repositories/pino-pretty/node_modules/js-joda-locale/node_modules/fsevents
> node install

[fsevents] Success: "/Users/matteo/Repositories/pino-pretty/node_modules/js-joda-locale/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/matteo/Repositories/pino-pretty/node_modules/js-joda-locale/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN js-joda-locale@1.0.0 requires a peer of cldr-data@* but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of cldrjs@^0.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of js-joda@^1.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of js-joda-timezone@^1.1.5 but none is installed. You must install peer dependencies yourself.

+ babel-preset-env@1.6.1
+ babel-plugin-add-module-exports@0.2.1
+ babel-loader@7.1.4
+ yargs@10.1.2
+ babel-core@6.26.0
+ webpack@3.11.0
+ webpack-build-notifier@0.1.23
added 574 packages from 359 contributors in 31.183s

> js-joda-locale@1.0.0 build_package /Users/matteo/Repositories/pino-pretty/node_modules/js-joda-locale
> node ./utils/build_package.js

98% [1] emitting
webpack: done.
npm WARN js-joda-locale@1.0.0 requires a peer of cldr-data@* but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of cldrjs@^0.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of js-joda@^1.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN js-joda-locale@1.0.0 requires a peer of js-joda-timezone@^1.1.5 but none is installed. You must install peer dependencies yourself.

removed 574 packages in 5.026s
added 753 packages from 457 contributors in 146.064s
```

Can we use some other dependency or ship an already built version of this module?

**Comment by jsumners** [comment]
@mcollina it's due to needing all of the locale data for supporting date and time localization. The other option would be to use the `moment` suite, but it's slower than `js-joda`.

I really don't think this is a big issue given that we have no intention of bundling this in core. It's meant to be a system utility.

**Comment by mcollina** [comment]
@jsumners can we ship the built version of this library? I still want to have the `prettyPrint: true` option that soft-load this, and that library adds a ton of install time. As they are webpacking it, we can just ship the webpacked stuff in a prepublish hook.

**Comment by jsumners** [comment]
I really don't know. Can you show me?

**Comment by mcollina** [comment]
As an example https://github.com/fastify/fastify-swagger/blob/master/package.json#L9.

**Comment by ilyaztsv** [comment]
> The other option would be to use the moment suite, but it's slower than js-joda

@jsumners may be [luxon](https://github.com/moment/luxon) or [date-fns](https://github.com/date-fns/date-fns) would be as an option to move from `js-joda`?

**Comment by jsumners** [comment]
@mcollina I don't even know what package is doing the webpack stuff. It's all imported directly from npmjs.com.

@ilyaztsv this is a pretty good summary of what is wrong with Moment https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189 but it also sounds like it wouldn't help with localization since it is missing locales and doesn't support timezones (yet)

**Comment by mcollina** [comment]
> @mcollina I don't even know what package is doing the webpack stuff. It's all imported directly from npmjs.com.

This is exactly why I'm 👎  to use js-joda. I think it's the locale thing (https://github.com/js-joda/js-joda-locale).  Can we do without?

**Comment by jsumners** [comment]
Not if we want to support displaying local times. It needs the locale information to work with timezones and offsets.

**Comment by mcollina** [comment]
@jsumners I'm a bit lost. In pino we currently have this functionality with no dependencies or are we adding something significant? What would we lose by removing this?

**Comment by jsumners** [comment]
@mcollina in pino we have the non-standard functions

https://github.com/pinojs/pino/blob/fc4c83bc0f202a5ec4d2a7b692b70cce0e0210b4/pretty.js#L33-L40
and
https://github.com/pinojs/pino/blob/fc4c83bc0f202a5ec4d2a7b692b70cce0e0210b4/pretty.js#L269-L298

By using a library dedicated to the task, we offload having to maintain date and time parsing and formatting. As is evidenced by this conversation: that's a monumental task.

However, it's possible one of these libraries could be sufficient:

https://www.npmjs.com/package/dateformat
https://www.npmjs.com/package/fecha
https://www.npmjs.com/package/date-format-lite

**Comment by mcollina** [comment]
I'm happy with whatever you decide, as long as it does not have a big dependency change.

**Comment by jsumners** [comment]
I have migrated to the `dateformat` module.

**Comment by jsumners** [comment]
With #4 merged I think we are ready for release. Agreed?

**Comment by davidmarkclements** [comment]
agreed

**Comment by jsumners** [comment]
Published.
