### ISSUE TITLE
Filter by level

### ISSUE THREAD

**Issue by cdhowie** [pinojs/pino-pretty#100]
Maybe I'm obtuse but I don't see a straightforward way to limit output to certain levels, at least not in a user-friendly way. Perhaps `-s` could be used to do this, but this requires the user remember how the numeric levels map to the friendly names. Coming from bunyan, it was nice to be able to specify `-l info` and have only messages at least as severe as the info level be displayed (filtering out debug and trace). I feel like this tool could benefit from such an option.

**Comment by mcollina** [comment]
Sure thing! Would you like to send a PR?

**Comment by cdhowie** [comment]
I'm willing to take a stab at it. An initial version won't support custom levels; that's probably a niche enough use case that it might not make sense to support it.

**Comment by mcollina** [comment]
I agree

**Comment by bitjson** [comment]
This feature would be appreciated. 👍

Until then, here are the queries for the default `pino` levels:

**`trace`**:
```
pino-pretty --search 'level >= `10`'
```
**`debug`**:
```
pino-pretty --search 'level >= `20`'
```
**`info`**:
```
pino-pretty --search 'level >= `30`'
```
**`warn`**:
```
pino-pretty --search 'level >= `40`'
```
**`error`**:
```
pino-pretty --search 'level >= `50`'
```
**`fatal`**:
```
pino-pretty --search 'level >= `60`'
```

**Comment by bitjson** [comment]
Previously I was using: `tail -f log.ndjson | pino-pretty -c -l -t --search 'level >= `20`'`, but the above workaround was broken by https://github.com/pinojs/pino-pretty/pull/227 (the `search` flag has been removed). 

@mcollina when you get a chance, how would you recommend filtering output by level now? 

Is this still a feature for which you'd consider a PR? How about `--minimumLevel` (`-L`) which would accept a number, `trace` (10), `debug` (20), `info` (30), `warn` (40), `error` (50), or `fatal` (60).

**Comment by bitjson** [comment]
Just made a PR for that design, but please feel free to close it and implement this feature a different way if that's not the right approach: https://github.com/pinojs/pino-pretty/pull/233

**Comment by jsumners** [comment]
It's really probably easier to pipe into `jq` before `pino-pretty`.
