### ISSUE TITLE
Programmatic integration with pino v6 doesn't respect log formatter

### ISSUE THREAD

**Issue by giannisp** [pinojs/pino-pretty#102]
Pino v6 has introduced the ability to custom format the log object via using the new `formatters.log` function:
https://github.com/pinojs/pino/blob/master/docs/api.md#log

Seems like on programmatic integration with the current pino-pretty version (3.6.1), the custom format is not reflected on the output.

**Comment by jsumners** [comment]
Please provide a reproducible test case to illustrate the issue at a minimum. If possible, a PR would be welcome to fix it.

**Comment by giannisp** [comment]
Thanks, I had a look around on the codebase.  
I think it's on the pino repo side that this needs to be fixed, similarly to how redact/serializer formatting is being applied for the "pretty" output.
