### ISSUE TITLE
Journalctl (not an issue)

### ISSUE THREAD

**Issue by Elexy** [pinojs/pino-pretty#105]
I just wanted to share how to get pretty logs from node running under systemd:
`sudo journalctl -u monitor -f -o cat | pino-pretty`

from the journalctl manual:
> cat 
generates a very terse output, only showing the actual message of each journal entry with no metadata, not even a timestamp.

**Comment by mcollina** [comment]
Nice @elexy! I think we should get this into https://github.com/pinojs/pino/blob/master/docs/help.md, if wouldn't mind to do a PR.
