### ISSUE TITLE
feature request: provide a way to disable warning that flushSync in pretty print is not supported

### ISSUE THREAD

**Issue by AleksandrSl** [pinojs/pino-pretty#108]
Use case: we understand that flushSync is not supported and use pretty print only in dev mode and we don't want to pollute logs with this warning.

**Comment by mcollina** [comment]
Would you be ok in sending a PR? I think the use case is valid.

**Comment by AleksandrSl** [comment]
I'll try to take a closer look and come up with pull request.

**Comment by AleksandrSl** [comment]
@mcollina I understood that this issue belongs more to the pino, should I close it here and move to pino repo? 
I also have one question about warning "mechanism". If I correctly understood flush sync, it's called when application is about to die, but in the code we check if user has been alredy warned. How it is possible to see two such messages? If we do several fatal logs? Are there any chances that this warning wouldn't be logged, due to the same reason as decsribed here (https://github.com/pinojs/pino/pull/740#discussion_r346788313)?
Can't we somehow log this warning just after application start when pretty stream has been created?

**Comment by AleksandrSl** [comment]
Maybe use something like this 
```
process.emitWarning(
    'The pino.extreme() option is deprecated and will be removed in v7. Use pino.destination({ sync: false }) instead.',
    { code: 'extreme_deprecation' }
  )
```
to warn that flushSync is unsupported?

**Comment by AleksandrSl** [comment]
Actually closed by https://github.com/pinojs/pino/pull/841
