### ISSUE TITLE
"this.$__path is not a function" cause by fast-safe-stringify

### ISSUE THREAD

**Issue by WangHansen** [pinojs/pino-pretty#109]
`this.$__path is not a function` error caused by `fast-safe-stringify` library when used with mongoose. It has been a issue for `fast-safe-stringify` for a while without fix: https://github.com/davidmarkclements/fast-safe-stringify/issues/43

Is it possible to swap to [safe-stable-stringify](https://github.com/BridgeAR/safe-stable-stringify) or provide an option to switch back to normal `JSON.stringify()`?

**Comment by mcollina** [comment]
Not right now, a PR is likely welcomed anyway.

**Comment by WangHansen** [comment]
Sure, currently safe-stable-stringify has a behavior of reordering the key of objects which breaks the tests. See [issue](https://github.com/BridgeAR/safe-stable-stringify/issues/17) I will wait until it is fixed to submit a PR.
