### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by zoonman** [pinojs/pino-pretty#111]
I have the following script to run in a regular terminal macOs Mojave.

```
nvm use

NODE_ENV=development npx dotenv-load ts-node src/bin/setup.ts start | pino-pretty -c
```

Here is the log line sample

```
{"level":10,"time":1593027861422,"pid":16628,"hostname":"zmMac.local","name":"setup","group":"main","msg":"Logger initialized"}
```

No colors or pretty print output.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/85620990-93a67080-b632-11ea-9aa0-e0ddb88dc1fc.png)

**Comment by zoonman** [comment]
Ok,it seems pino-pretty doesn't handle stderr because it works like this:

```
 npm run start:dev 2>&1 > /dev/null | pino-pretty -c
```

**Comment by jsumners** [comment]
It reads the standard input. Just like any other standard Unix tool.

**Comment by zoonman** [comment]
I got your point.
