### ISSUE TITLE
[Q] Pino Pretty for Production

### ISSUE THREAD

**Issue by fortezhuo** [pinojs/pino-pretty#115]
I want to ask about this below statement, So can pino-pretty be used for production by piping out CLI ?
 
```
It's recommended to use pino-pretty with pino by piping output to the CLI tool:
pino app.js | pino-pretty
```

And if pino pretty can't be used for production, so how the best way for formatting or consume and store pino log for production env ?

**Comment by mcollina** [comment]
JSON is a great format for producing machine-readable logs.

**Comment by fortezhuo** [comment]
Thanks for your reply @mcollina. Sorry to bother, and can we use piping output pino transport for production env ? Or can you suggest another suitable / best approach or documentation for consume pino log on production env ?

**Comment by mcollina** [comment]
What do you mean by “consume”?

**Comment by fortezhuo** [comment]
If we can't pretty print the log, we want to store (consume) the log to our database. So can we use piping CLI of pino transport for production env ? Or you can suggest best approach for how to store pino log to database ?

**Comment by mcollina** [comment]
store the JSON lines as individual elements in your database, as an example use elasticsearch/kibana/beats etc.

**Comment by fortezhuo** [comment]
Noted. And I found pino-elasticsearch, and can I use CLI like "node app.js | pino-elasticsearch" on production env ?

```
pino-elasticsearch

pino-elasticsearch uploads the log lines in bulk to Elasticsearch, to be displayed in Kibana.

It is extremely simple to use and setup

$ node app.js | pino-elasticsearch
```

**Comment by mcollina** [comment]
Yes exactly.
