### ISSUE TITLE
How do you hide the "(pid on hostname)" part?

### ISSUE THREAD

**Issue by bendavis78** [pinojs/pino-pretty#122]
I don't want to see the part of the log that says "(123456 on hostname)". How can I customize that?

**Comment by jsumners** [comment]
Have you read through our documentation?

**Comment by bendavis78** [comment]
Ah, I see it's through the ignore option. That wasn't totally obvious at first.

**Comment by jsumners** [comment]
Do you think the documentation needs to be improved?

**Comment by cole-themeta** [comment]
It would be nice to be able to remove them from the top log message without removing them from the properties below the message. And yes, the docs do not make it clear that removing those keys from the properties will also remove them from the top level log message
