### ISSUE TITLE
 When using the argument --config ignored argument  --messageFormat 

### ISSUE THREAD

**Issue by gulamsounov** [pinojs/pino-pretty#126]
I have a config file .pino-prettyrc.json

```
{
  "messageFormat ": "{level} - {pid}"
}
```
I run like this:
`pm2 log sql-exchanger --raw | pino-pretty --config /mnt/node01/app/sql-exchanger/.pino-prettyrc.json`

And I see the log as:
`[1598537082720] INFO  (21622 on Node01): Test`

But the format is different.

**Comment by jsumners** [comment]
What is the issue? What do you expect to see?

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gulamsounov** [comment]
I figured it out. The problem was "messageFormat " -> "messageFormat"
Thanks
