### ISSUE TITLE
"v" field disappear from logged object

### ISSUE THREAD

**Issue by AviBueno** [pinojs/pino-pretty#127]
Hi, I'm new to pino/pino-pretty.
Trying to pass the following object through pino-pretty:

```
{
  u: 0,
  v: 1,
  w: 2
}
```

Ends up like this:

```
{
  u: 0,
  w: 2
}
```

Seems like this is a direct result of PR pinojs/pino#623, which addresses issue pinojs/pino#620.
Now, removing a Bunyan remnant is cool. Removing a user-data property is... less cool.
Could this be fixed?

Thanks.

**Comment by jsumners** [comment]
It seems to me this is solved by doing `log.info({ data: { u:0, v:1, w:2 } })`.

https://github.com/pinojs/pino-pretty/blob/852fdf707c1a57627a3f523b0cec8824e5d24ab4/lib/utils.js#L150-L157

**Comment by mcollina** [comment]
I think it's ok to remove v from there.

**Comment by jsumners** [comment]
Sure. It'd just be a major bump.
