### ISSUE TITLE
Leading space for ignore time and level

### ISSUE THREAD

**Issue by davesteinberg** [pinojs/pino-pretty#129]
If I use `--ignore` tp exclude the time and level, I get an unwanted leading space on each line. For example:

```
echo '{"level":30,"time":1599275372412,"pid":26631,"hostname":"pb","name":"server","msg":"Hello, world!"}' \
  | npx pino-pretty --ignore "time,level"
```

This yields:

```
 (server/26631 on jitterbug): Hello, world!
```

Note the space at the beginning of the line.

I seem to get this space regardless of whether or not I ignore additional keys or which ones. What I'm actually trying to do is display just the message:

```
echo '{"level":30,"time":1599275372412,"pid":26631,"hostname":"pb","name":"server","msg":"Hello, world!"}' \
  | npx pino-pretty --ignore "time,level,name,pid,hostname"
```

Again, this includes a leading space:

```
 Hello, world!
```

This seems like a bug, but I'm not sure. Is there a reason for including the space? I'd much prefer not to have it there.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by davesteinberg** [comment]
@mcollina I'll give it a try.
