### ISSUE TITLE
Ignoring nested properties 

### ISSUE THREAD

**Issue by hugomallet** [pinojs/pino-pretty#132]
Hello,

It looks like it is not possible to ignore nested properties.
It would be cool if we could ignore for example `--ignore req.headers,req.id` without ignoring completely the object req.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by acidoxee** [comment]
Hi, thanks for this update, unfortunately this seems to un-ignore keys that are composed of dots. For instance, we have a bunch of `logging.googleapis.com/xxxxxx` keys for GCP, which now can't be ignored.

**Comment by jsumners** [comment]
@acidoxee please open a new issue and reference the PR that introduced the problem. This issue should have been closed with the PR merge.
