### ISSUE TITLE
Incorrect messageFormat output for level

### ISSUE THREAD

**Issue by dublx** [pinojs/pino-pretty#133]
According to the README for option `--messageFormat`:

```md
--messageFormat (-o): Format output of message, e.g. {level} - {pid} will output message: INFO - 1123```
```

But this is not currently the case, instead, the `level` raw value is returned, eg:

```js
pino.info('hello world')
```

will result in 

```sh
$ node example.js | pino-pretty -c -t -o '{level} - {pid} {msg}'
[2020-09-24 15:06:25.810 +0000] INFO  (51870 on user.local): 30 - 51870 hello world
```

If this a README inconsistency or is it missing the logic in the code?

**Comment by mcollina** [comment]
the level can be customized in all possible ways. It normally comes as a number but it can come in all possible ways.
https://github.com/pinojs/pino-pretty/blob/ee30e8bc9ef8df1e8954d8ad07c65c5f4aa1cd69/lib/utils.js#L165-L182 < we might want to expose a function to do this.

**Comment by jsumners** [comment]
I think the documentation is wrong. The test is clearly showing that it will output the value -- https://github.com/pinojs/pino-pretty/blob/ee30e8bc9ef8df1e8954d8ad07c65c5f4aa1cd69/test/lib/utils.public.test.js#L104-L107

https://github.com/pinojs/pino-pretty/pull/88

**Comment by dublx** [comment]
Does anyone know why there is a trailing space in the INFO and WARN?
On purpose or ok to remove it?
https://github.com/pinojs/pino-pretty/blob/1dfaa9c25bea017feb1792a76654274f1031340b/lib/constants.js#L18-L19

CC @mcollina @jsumners

**Comment by dublx** [comment]
Proposed support for a new option `levelLabel`:

```sh
$ pino-pretty -h
  Usage: pino pretty [options] [command]
...
  Options:
....
    -b, --levelLabel [value]    Output the log level using the specified label (defaults to "levelLabel")
```

Example usage (default is `levelLabel`):
```sh
node example.js | pino-pretty -c -t -o '[{level}] {levelLabel} - {pid} {msg}'
[2020-09-28 14:34:52.783 +0000] INFO (61621 on user.local): [30] INFO - 61621 hello world
```

Example usage with a custom value `--levelLabel` or `-b`:
```sh
$ node example.js | pino-pretty -c -t --levelLabel 'xyz' -o '[{xyz}] {levelLabel} - {pid} {msg}'
[2020-09-28 14:40:40.082 +0000] INFO (61812 on user.local): [INFO]  - 61812 hello world
```

Feedback welcome
CC @mcollina @jsumners

**Comment by jsumners** [comment]
> Does anyone know why there is a trailing space in the INFO and WARN?


Yes. https://github.com/pinojs/pino-pretty/pull/47
