### ISSUE TITLE
messageFormat is not applied when setting up pino programmatically

### ISSUE THREAD

**Issue by Ricket** [pinojs/pino-pretty#138]
I followed the instructions from pino and pino-pretty, as best I can tell, but cannot get messageFormat to work. My usage is like this:

```
const log = require('pino')({
  prettyPrint: {
    messageFormat: '{level} {time} {foo} {msg}'
  }
})

log.info('hello world')
```

and the output is in the default format:

```
[1605372973611] INFO	 (15763 on ricketmb): 30 1605372973611  hello world
```

I [created a test app](https://github.com/Ricket/pino-format-broken) which you can use to reproduce the issue.

I am using node v12.16.3 because this is the version of the latest stable electron (it's about to move to 14 but last I checked only nightlies). pino and pino-pretty freshly installed from npm of course; 6.7.0 and 4.3.0 respectively.

**Comment by mcollina** [comment]
This look like a bug somewhere in the stack. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
From the looks of it, `messageFormat` looks somehow broken.

It seems `messageFormat` formats the _message_ part of the log line, and not the whole line: note that `30 1605372973611  hello world` matches your format, there is just some stuff that should be there at the beginning.

**Comment by mcollina** [comment]
wdyt @jsumners?

**Comment by jsumners** [comment]
It's pretty clear the feature was designed to only format the `msg` property -- https://github.com/pinojs/pino-pretty/pull/88

**Comment by mcollina** [comment]
Ok, then it's totally ok :).
