### ISSUE TITLE
Lots of spaces after TRACE, but not so after INFO

### ISSUE THREAD

**Issue by emonddr** [pinojs/pino-pretty#140]
I am using fastify with pino and pino pretty.

I see lots of spaces after the TRACE keyword, but not after the INFO keyword.

```
[2020-12-15T20:33:16:892Z] INFO : Server listening at http://127.0.0.1:3000
[2020-12-15T20:33:28:275Z] TRACE        : [c0c93293-5093-40bf-8d32-76a61287fba7] \/ Entering [POST /someEndPoint]
```

I tried creating a custom prettifier for the 'level' field, but it is never called.

Any insight is appreciated.

thx

:)

**Comment by jsumners** [comment]
See https://github.com/pinojs/pino-pretty/pull/135

**Comment by emonddr** [comment]
@jsumners , that for the link.

 I am still seeing the large gap between the TRACE string and the beginning of the string I actually sent to fastify.log.trace() .  what version of pino-pretty contains the fix above?

I am using
```
 "pino-pretty": "^4.3.0",
```

I also have these options set

```
level: 'trace',
  prettyPrint: {
    ignore: 'pid,hostname',
    translateTime: `UTC:yyyy-mm-dd'T'HH:MM:ss:l'Z'`,
  },
```

**Comment by emonddr** [comment]
Also, I don't have a custom prettifier for 'level' defined when this large gap is occurring.

**Comment by jsumners** [comment]
I am saying that PR #135 introduced tabs as alignment tokens. So this is likely a bug. Personally, I'd rather just revert back to not trying to align these fields. But if you, @Zirak, and @dublx would like to collaborate on a fix that retains the formatting, that would be okay as well.

**Comment by arthurw1** [comment]
I'm observing something similar too. See below:

![image](https://user-images.githubusercontent.com/75303606/103052127-561ba380-45d3-11eb-8ec6-1634a2ded482.png)

**Comment by mcollina** [comment]
This issue needs somebody to work on it, volunteers are welcome :).

**Comment by arthurw1** [comment]
@mcollina I can take this on!

**Comment by mcollina** [comment]
go for it!
