### ISSUE TITLE
Is there a way to parse multiline logs?

### ISSUE THREAD

**Issue by mallowigi** [pinojs/pino-pretty#147]
Hi, just discovered this, looks pretty rad. I was wondering though if there was a way to parse semantic logs spanning over multiple lines. Something like 

```json
{
  "level": 2,
  "payload": {
    "blabla": "bla"
  },
  "msg": "Something happened"
}
```

**Comment by jsumners** [comment]
This is answered in the first sentence of the readme:

> This module provides a basic ndjson formatter.
