### ISSUE TITLE
tests failing in v4.17.5

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino-pretty#16]
due to https://github.com/pinojs/pino/issues/456

it should be fine to fix the pino-pretty test

cc @mcollina @jsumners

**Comment by jsumners** [comment]
But the test isn't broken. It explicitly looks for the `null` serialization because https://github.com/pinojs/pino/issues/382

**Comment by disintegrator** [comment]
Hey folks, is someone looking at this or shall I pick it up? I wasn't aware of the integration suite when I was creating my PR 🤦‍♂️
@jsumners My change in https://github.com/pinojs/pino/pull/457 caused this by preventing the stack property from being printed in the JSON output if it is false-y.
I can think of a couple of ways forward:
- If you want the logger to emit `"stack": null` then I'd need to update my fix
- If we are happy to not output stack if it is false-y then the test needs to be updated

Any other suggestions?

**Comment by davidmarkclements** [comment]
If you update your fix it will be a major - which is fine because we are close to releasing v5 - see the next-major branch 

However for v4 it can't be an update so we need to change the expectation in pino-pretty 

Please feel free to PR!

@mcollina do you concur
