### ISSUE TITLE
Gray out meta information when using --singleLine option when coloring is enabled

### ISSUE THREAD

**Issue by gr2m** [pinojs/pino-pretty#160]
I really like the single-line output introduced in https://github.com/pinojs/pino-pretty/issues/97 🙇🏼🙏🏼 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/39992/109695438-bdf4ea00-7b40-11eb-9add-e64d7350d204.png">

I wonder if we could gray out the meta information by default, when coloring is enabled?

<img width="501" alt="image" src="https://user-images.githubusercontent.com/39992/109695684-0c09ed80-7b41-11eb-9977-dff2f8ad375b.png">

I think that makes the logs more readable. 

If you'd like that change, I'd appreciate a pointer on how the change would be done. I looked into `lib/utils.js` but I'm not sure how that change would be implemented, other than requiring `chalk` in this file and making this change

```diff
-       result += stringifySafe(plain)
+       result += chalk.gray(stringifySafe(plain)
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gr2m** [comment]
there you go: https://github.com/pinojs/pino-pretty/pull/161

**Comment by pilpelbarkan** [comment]
is there a way to change the color of the meta data when using the `singleLine` option? the gray is a bit too dark and makes it hard to read

**Comment by jsumners** [comment]
Please open a separate issue if you are having trouble with a feature.
