### ISSUE TITLE
singleLine Missing from TypeScript Types

### ISSUE THREAD

**Issue by adarnon** [pinojs/pino-pretty#168]
When using the `prettyPrint` option passed to `pino()`, the CLI option `singleLine` is missing from the `PrettyOptions` interface. Passing this option works, but type checking fails because this option is not documented.

**Comment by jsumners** [comment]
This module does not include any TypeScript.

**Comment by aerdnach** [comment]
This has been fixed few days ago on @types/pino. Now the option is available in pino types.
