### ISSUE TITLE
Keep colorizing of console.log in console output with default colors

### ISSUE THREAD

**Issue by MurzNN** [pinojs/pino-pretty#170]
When I launch the app without `pino-pretty`, it have colored `console.log` dumps, but not-prettied `pino` output, example:
![image](https://user-images.githubusercontent.com/336662/113134248-40002d80-9229-11eb-8f4a-00a5daf02e62.png)
But when I attach `pino-pretty` via
```
node app.ts | pino-prettier
```
the `pino` logs are looks colorized and best, but colorizing of `console.log()` is disappearing:
![image](https://user-images.githubusercontent.com/336662/113134276-44c4e180-9229-11eb-9790-ccdb6e2b858f.png)

The question is how to keep both items colorized together in output?

Here is the testing code:
```js
import * as pino from "pino";
const logger = pino.default();
let test = { fullName: "Alice", "age": 47 };
console.log(test);
logger.info(test, 'hello world');
```

**Comment by mcollina** [comment]
It's not possible. You'd need to run pino-pretty in process with the prettyPrint option.
