### ISSUE TITLE
Unable to customize log line

### ISSUE THREAD

**Issue by glensc** [pinojs/pino-pretty#171]
Seems that certain part of the log line is not customizable:

```ts
#!/usr/bin/env node -r ts-node/register

const pino = require('pino')
const logger = pino({
  prettyPrint: {
    colorize: true,
    messageFormat: '{msg}',
  },
})

logger.info('hi')
```

This prints:

```
[1617202169846] INFO (68773 on rocinante): hi
```

It should print only `{msg}`:

```
hi
```

How to customize removal of the ugly timestamp, redundant pid and hostname?

**Comment by glensc** [comment]
Seems besides `messageFormat` the hardcoded things are controlled by `timestampKey` and `ignore`:

I can achieve expected result with:

```js
    ignore: 'pid,hostname,time',
```

and 

```js
    timestampKey: false,
    ignore: 'pid,hostname',
```

what is their difference, which I should use and why?

**Comment by mcollina** [comment]
> what is their difference, which I should use and why?

Whatever works for you.
