### ISSUE TITLE
If msg is a number its removed from output

### ISSUE THREAD

**Issue by e3tegi** [pinojs/pino-pretty#181]
https://github.com/pinojs/pino-pretty/blob/d9fc678fb546c466e9df02cd8eb4da35a8c26e7e/lib/utils.js#L226

Why delete the msg if its a number?

**Comment by mcollina** [comment]
Would you like to send a Pull Request to add the support for it? Remember to add unit tests.

**Comment by 10xLaCroixDrinker** [comment]
This was fixed in #434
