### ISSUE TITLE
Seems to be no way to remove the brackets of the timestamp?

### ISSUE THREAD

**Issue by airship-shrimp** [pinojs/pino-pretty#185]
Can I achieve it in some way?

**Comment by jsumners** [comment]
Not with a PR to implement such a feature.

https://github.com/pinojs/pino-pretty/blob/7693cd4810ab7b9589f33364148d0cd33119dd42/lib/utils.js#L390-L405

**Comment by pearofducks** [comment]
@airship-shrimp - once 7.3.0 (assuming this is the version) is released, you'll be able to use `customPrettifiers.time` to customize this and remove the brackets.

**Comment by Fdawgs** [comment]
closed by #263
