### ISSUE TITLE
Unexported interface PrettyOptions causes type-check error in @types/pino

### ISSUE THREAD

**Issue by squidini** [pinojs/pino-pretty#189]
This kind of breaks pino with `TS2694: Namespace '"/node_modules/pino-pretty/index"' has no exported member 'PrettyOptions'.`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L546

[![image](https://user-images.githubusercontent.com/77545839/119976079-46a7e880-bfbf-11eb-95ec-6badd06c1a09.png)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L546)

**Comment by kibertoad** [comment]
On it.
