### ISSUE TITLE
req.url is not working

### ISSUE THREAD

**Issue by reach009** [pinojs/pino-pretty#196]
Hi guys,

I am having this problem where I try to print out the request url on my logger. Below is my pino-pretty configuration mixed with express-pino-logger:

```js
const pino = require("pino");
const expressPino = require("express-pino-logger");

const logger = pino({
  level: process.env.LOG_LEVEL || "info",
  prettyPrint: {
    translateTime: "SYS:standard",
    colorize: true,
    messageFormat: `url:{req.url} - {msg}`
  },
});

const expressLogger = expressPino({ logger });

module.exports = { logger, expressLogger };
```

The output is as the screenshot:

![image](https://user-images.githubusercontent.com/35024397/120916299-6f289480-c6db-11eb-96b9-a1805de3669c.png)

Please kindly advise.

**Comment by mcollina** [comment]
Can you provide a full, runnable
example to reproduce your problem? From the log lines you are showing, you are logging this without using `req.log`.

**Comment by reach009** [comment]
@mcollina : Please refer to my example below: 

// display all notes
router.get("/notes", auth, async (req, res) => {
  try {
    const notes = await Note.find({ userId: req.user });
    logger.info("Retrieve all notes from user id : " + req.user);

    res.json(notes);
  } catch (err) {
    logger.error(err);
    res.json(err);
  }
});

**Comment by mcollina** [comment]
You need to call `req.log.info()` etc instead.

**Comment by reach009** [comment]
Not working , man.

![image](https://user-images.githubusercontent.com/35024397/121023560-f78b6000-c7d5-11eb-8f00-ba4f29ff226e.png)

**Comment by mcollina** [comment]
You are still using the parent logger.

```js
// display all notes
router.get("/notes", auth, async (req, res) => {
  try {
    const notes = await Note.find({ userId: req.user });
    req.log.info("Retrieve all notes from user id : " + req.user);

    res.json(notes);
  } catch (err) {
    req.log.error(err); // <-- this
    res.json(err);
  }
});
```

**Comment by reach009** [comment]
![image](https://user-images.githubusercontent.com/35024397/121703948-e27c3d00-cb05-11eb-81b3-d8231cd2854f.png)

**Comment by mcollina** [comment]
are you registering the logger middleware? Can you upload an example that we can run?

**Comment by reach009** [comment]
@mcollina : Yup, I did register the logger. 

How about we try a simple request as below:

## logger.js

```
const pino = require("pino");
const expressPino = require("express-pino-logger");

const logger = pino({
  level: process.env.LOG_LEVEL || "info",
  prettyPrint: {
    translateTime: "SYS:standard",
    colorize: true,
    messageFormat: `url:{req.url} - {msg}`
  },
});

const expressLogger = expressPino({ logger });

module.exports = { logger, expressLogger };
```

## index.js
```
/ jshint esversion: 6

const express = require("express");
const cors = require("cors");
const app = express();

// logs
const { logger } = require("./logger");

// make use of express
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

// allow cors
app.use(cors());

// calling routes
app.use("/api", require("./router"));

const port = process.env.PORT || 5000;
app.listen(port, (req, res) => {
  logger.info(`server listening on port: ${port}`);
});
```

## router.js
```
const express = require("express");
const router = express.Router();
const {logger} = require("./logger");

router.get("/test", async (req, res ) => {
  logger.info("Hello, this is just a test!!!");
  res.send("test");
})

module.exports = router;
```

**Comment by mcollina** [comment]
You need to add:

```js
app.use(expressLogger)
```

**Comment by reach009** [comment]
> You need to add:
> 
> ```js
> app.use(expressLogger)
> ```

It works now. Thank you so much for helping.
