### ISSUE TITLE
Emits nothing, exits with no error if translateTime sees a string for a time

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [pinojs/pino-pretty#198]
```shell
(
  echo '{"time":"1623170292956","msg":"one"}'
  echo '{"time":1623170292956,"msg":"two"}'
) | npx pino-pretty --translateTime
```
Emits nothing at all and exits with success (0). It should _at least_ emit for the "valid" second line, and arguably should emit _something_ for the first sort-of-invalid line.

**Comment by mcollina** [comment]
Good spot! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mgabeler-lee-6rs** [comment]
I'll be happy to do so if I have the time, but I'll be honest that doesn't look promising over the next week-ish.
