### ISSUE TITLE
Is there a way in pino pretty where I can make show the json in a normal way rather than formatted

### ISSUE THREAD

**Issue by vmwhereqa** [pinojs/pino-pretty#200]

**Comment by mcollina** [comment]
How is this different from not using pretty-print? What output would you have in mind?

**Comment by vmwhereqa** [comment]
I like the color and the way we can customize stuff, but instead of showing json like this:
<img width="455" alt="Screenshot 2021-06-22 at 15 21 06" src="https://user-images.githubusercontent.com/63970843/122931872-90d97b00-d36d-11eb-88a4-48cf903db8a7.png">

I would like to see like this.
![image](https://user-images.githubusercontent.com/63970843/122932160-c9795480-d36d-11eb-9a56-9e8f7f4e2722.png)

so I want to know if there is any option to use pretty pino but show json without intendation of expanding

**Comment by jsumners** [comment]
You will need to write your own prettifier.
