### ISSUE TITLE
Switch from chalk to colorette

### ISSUE THREAD

**Issue by kibertoad** [pinojs/pino-pretty#208]
See https://www.npmjs.com/package/colorette
2x faster, cleaner implementation, zero dependencies.

If there is an approval, I can give it a shot. Migration for knex was really straightforward back in the day: https://github.com/knex/knex/pull/2718

**Comment by mcollina** [comment]
Sure, it seems also to ship a cjs version. go ahead!

**Comment by kibertoad** [comment]
Currently blocked by https://github.com/jorgebucaran/colorette/issues/61

**Comment by mcollina** [comment]
I'm ok for that code to be part of pino-pretty if you prefer.

**Comment by kibertoad** [comment]
@mcollina Generally I would prefer to see this functionality upstream, the only reason  why it might be preferable to have it in pino-pretty is being able to lock to slightly older version to avoid stumbling upon https://github.com/jorgebucaran/colorette/issues/48. Do we officially support Node 13?

**Comment by mcollina** [comment]
I'm ok to bump minimum Node.js to v12.x, v14.x and v16.x all at their latest.

We'll bump the major.
