### ISSUE TITLE
shortcut -a won't work

### ISSUE THREAD

**Issue by mvhirsch** [pinojs/pino-pretty#212]
Hi, I'm using pino-pretty on another logger, so I need to change the timestamp key like this:

```
# expected ts to be timestamp key
$> echo '{"ts":1623170292956,"msg":"one"}' | pino-pretty -a ts
one
    ts: 1623170292956
```

But it won't translate it correctly. After trial and error I found out, that the long version will do the trick:

```
# works
$> echo '{"ts":1623170292956,"msg":"one"}' | pino-pretty --timestampKey ts
[1623170292956]: one
```

Looks like the shortcut `-a` isn't working correctly.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by micalevisk** [comment]
Note that this happens to all options listed bellow. Their short version cannot be used due to this bug.

https://github.com/pinojs/pino-pretty/blob/141ca39701b2bca61b1dd4e5c7ff05aa5300884b/bin.js#L70-L72

---

Looks like we should pass the `alias` option to `mri` as well to fix that

```js
let opts = args.parse(process.argv, {
  mri: {
    alias: {
      messageKey: 'm',
      timestampKey: 'a'
    },
    default: {
      messageKey: DEFAULT_VALUE,
      levelKey: DEFAULT_VALUE,
      timestampKey: DEFAULT_VALUE
    }
  }
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
