### ISSUE TITLE
Should be an optional peer dependency on pino

### ISSUE THREAD

**Issue by vjpr** [pinojs/pino-pretty#221]
Does not work with pnpm.

**Comment by jsumners** [comment]
There is not any information in this issue. Closing.

**Comment by vjpr** [comment]
Because pino requires pino-pretty when prettyPrint: true, it should be listed as an optionalPeerDependency.

**Comment by vjpr** [comment]
Like this:


"peerDependencies": { 
  "winston": "> 1.0.0 <= 1.2.10",
  "foo": "~2.3.0"
},
"peerDependenciesMeta": {
  "winston": {
    "optional": true
  }
}

**Comment by jsumners** [comment]
https://getpino.io/#/docs/pretty?id=api-example

> 1. Install a prettifier module as a separate dependency, e.g. npm install `pino-pretty`.

**Comment by vjpr** [comment]
Doesn't work for `pnpm` and `yarn 2`. This erroneously relies on modules being hoisted to the project's `node_modules` dir.
