### ISSUE TITLE
Change messageKey but have plain JSON

### ISSUE THREAD

**Issue by skliarovartem** [pinojs/pino-pretty#241]
I use nestjs-pino and  need to change message key, and as I see I can do it only by using this lib, but I also need to keep it as a plain JSON with custom message key.

Is it possible? Or I need to go by another way?
Many thanks!

**Comment by jsumners** [comment]
I do not understand this issue. We do not maintain `nestjs-pino`.

**Comment by skliarovartem** [comment]
Is it possible to pino-pretty to change message key only, but don't beatify JSON and keep it by itself?

**Comment by jsumners** [comment]
> Is it possible to pino-pretty to change message key only, but don't beatify JSON and keep it by itself?

That is completely contrary to the purpose of this module.

**Comment by skliarovartem** [comment]
Ok, delete it please, my mistake, messageKey is part of another lib, but not pino-pretty, sorry!
