### ISSUE TITLE
What is the new expected programmatic usage

### ISSUE THREAD

**Issue by PabloSzx** [pinojs/pino-pretty#246]
![Screenshot from 2021-10-14 12-32-18](https://user-images.githubusercontent.com/8672915/137349855-476e01de-f3d6-40d1-8d22-352acbba9464.png)

What is the new expected programmatic usage for pino v7? the docs are showing deprecated usage https://github.com/pinojs/pino-pretty#programmatic-integration

**Comment by PabloSzx** [comment]
[@types/pino](https://npm.im/@types/pino) doesn't have the "transport" field :disappointed: I had to add a `@ts-expect-error`, there I created the pr @mcollina

**Comment by kibertoad** [comment]
@PabloSzx https://github.com/pinojs/pino/pull/1156 takes care of that, stay tuned.
