### ISSUE TITLE
[Feature Request] `hideObject` accept array of properties name

### ISSUE THREAD

**Issue by latipun7** [pinojs/pino-pretty#251]
## Case
I don't want to hide all object in the log, only some specific property.

I utilize `messageFormat` to show the custom property. So it's make sense to hide that property in the object.
Given this snippet:
```js
const str = prettifyMessage({ 
  log: { msg: 'foo', context: 'appModule', otherProp: 'ok', hideThis: 'yes' }, 
  messageFormat: '{context} - {msg}',
})
```
currently it would logged as:
```bash
[234234124] INFO (1234 on hostname-XXX): appModule - foo
    context: "appModule"
    otherProp: "ok"
    hideThis: "yes"
```

## Possible Solution and Expectation
with the option `messageFormat` to accept array of the property name, it would hide that specific property instead of hiding all object.
```bash
$ node example.js | pino-pretty --hideObject context,hideThis

// output
[234234124] INFO (1234 on hostname-XXX): appModule - foo
    otherProp: "ok"
```

## Info
| tool          | version |
|---------------|---------|
| `pino-pretty` | 7.1.0   |
| `node`        | 14.18.0 |

**Comment by Schloemicher** [comment]
i use `--ignore` (`-i`) for the same effect

**Comment by BCsabaEngine** [comment]
> i use `--ignore` (`-i`) for the same effect

Thx, it really works.
