### ISSUE TITLE
Missing error log

### ISSUE THREAD

**Issue by ramiel** [pinojs/pino-pretty#26]
I have a strange situation. My code is

```js
try {
   throw new Error('an error');
} catch(e) {
  logger.error(e)
}
```

If I enable pino-pretty programmatically, the trace of the error is missing and the log line is

`[1534924057159] ERROR (16193 on here):`

If instead I pipe the output of pino to pino-pretty, the error is correctly shown

```
[1534924260199] ERROR (16798 on here): an error
    Error: an error
        at REQUEST
 (/test.js:43:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ramiel** [comment]
Oh, the version I'm using are

```
 ❯ npm ls pino pino-pretty                                                                                                                                                           
├── pino@5.0.1
└── pino-pretty@2.0.1
```

**Comment by mcollina** [comment]
Update your dependencies, this should be fixed in the latest.

**Comment by ramiel** [comment]
Thanks for the quick response. It worked!
