### ISSUE TITLE
Don't append space after key if prettified object begins with a newline

### ISSUE THREAD

**Issue by mojavelinux** [pinojs/pino-pretty#265]
When the singleLine option is not enabled, the prettifyObject function always inserts a space between the key and value. However, a custom prettifier function may return a string that begins with a newline (eol character) in the case it wants to do its own formatting of the value. In this case, the prettifyObject function leaves a space at the end of the line with the key.

I'd like to request that prettifyObject only insert a space between the key and the value if the value does not start with a newline.

Here's an example of when this happens:

```js
const pino = require('pino')
const pinoPretty = require('pino-pretty')

const logger = pino({}, pinoPretty({
  destination: 2,
  customPrettifiers: {
    key: () => '\n  prettified value\n  using our own formatting',
  },
}))

logger.info({ key: 'value' }, 'hello')
```

**Comment by mojavelinux** [comment]
The logic to implement this is rather straightforward:

```js
result += `${ident}${keyName}:${joinedLines.startsWith('\n') ? '' : ' '}${joinedLines}${eol}`
```

**Comment by mojavelinux** [comment]
A similar case could be made if the value returned by the custom prettifier is an empty string. However, that situation doesn't come up in my application.

**Comment by jsumners** [comment]
Is it really necessary? What is the case where the trailing space is visible?

**Comment by mojavelinux** [comment]
It was a test in my test suite that detect it. Is it necessary to fix? I think it's untidy and there's no other way to remove it before the message is sent to the output stream. Plus, it's a very simple fix that I'm happy to send. So yes, I'd like to see it cleaned up.
