### ISSUE TITLE
When an Error is the first parameter, the second and third parameters are not printed

### ISSUE THREAD

**Issue by ejwalker** [pinojs/pino-pretty#27]
Code is:

`try { throw new Error('foo') } catch(error) { logger.info(error, 'something went wrong') }`
`try { throw new Error('bar') } catch(error) { logger.info(error, 'something broke', 'test string') }`

The logger only prints the error for the first argument but not the second or third arguments:

`[1535020164640] INFO (94172 on macbook-pro-2.internal.local): foo
    Error: foo
        at Object.<anonymous>...
`
`[1535020164642] INFO (94172 on macbook-pro-2.internal.local): bar
    Error: bar
        at Object.<anonymous>... 
`

I would expect the second and third parameters to be outputted along with the error. 

Versions used are `pino@5.3.0` and `pino-pretty@2.0.1`

**Comment by eadaniel** [comment]
I looked into the issue and found out that pino does not pass the second argument to pino-pretty, it just passed following properties:

```js
{
  level: 30,
  msg: 'foo',
  time: 1535027646123,
  v: 1,
  pid: 46917,
  hostname: 'local',
  type: 'Error',
  stack: '...'
}
```

I reproduced it by linking pino-pretty to my project and adding a `console.log('INPUT DATA', inputData)` to the [pretty function](https://github.com/pinojs/pino-pretty/blob/master/index.js#L93).

**Comment by ejwalker** [comment]
Thank you @eadaniel for looking into this issue and finding the source of the problem.

Closing this issue here and will open another issue with pino.
