### ISSUE TITLE
Logs in terminal are out of order (by date) on different levels

### ISSUE THREAD

**Issue by frzsombor** [pinojs/pino-pretty#275]
Creating the issue here, as I suspect that this bug(?) is coming from pino-pretty and not pino itself.

Using the following code I wanted to achive that 4 different levels are logged into 4 different files (with dedupe turned on) and also the most important levels (info and error) are shown on the screen in the terminal window.

```javascript
'use strict';

const fs = require('fs');
const pino = require('pino');
const pretty = require('pino-pretty');

module.exports = () => {
    const customLevels = {
        debug   : 1,
        info    : 2,
        network : 3,
        error   : 4,
    };

    const pinoOpts = {
        base      : undefined, //avoid adding pid, hostname properties
        timestamp : pino.stdTimeFunctions.isoTime,
        level     : 'debug', //MUST be set at the lowest level of the destinations
        nestedKey : 'object',
        useOnlyCustomLevels: true,
        customLevels: customLevels,
        formatters: {
            level (label, number) {
                return { level: label };
            },
        },
    };

    const multistreamOpts = {
        dedupe: true, //send logs only to the stream with the higher level
        levels: customLevels,
    };

    const streams = [
        { level : 'debug',   stream : fs.createWriteStream(`./log/log-debug.log`,   { flags: 'a' }) },
        { level : 'info',    stream : pretty() },
        { level : 'info',    stream : fs.createWriteStream(`./log/log-info.log`,    { flags: 'a' }) },
        { level : 'network', stream : fs.createWriteStream(`./log/log-network.log`, { flags: 'a' }) },
        { level : 'error',   stream : pretty() },
        { level : 'error',   stream : fs.createWriteStream(`./log/log-error.log`,   { flags: 'a' }) },
    ];

    return pino(pinoOpts, pino.multistream(streams, multistreamOpts));
};
```

With this code, I found a strange anomaly in terms of the order of the logs.
If the logs are coming from different levels, they could be shown in the terminal in a mixed order of date.
Example:

```javascript
logger.info(`This is a simple text`);
logger.info({ this: 'is', an: 'object' });
logger.error(new Error('Invalid blah blah'));
```

As you can see in the following image, for some reason (maybe because the second line is an object?) the log with the "error" level is shown in the terminal before the second log with "info" level, even if you can see from the dates, that they are swapped:

![image](https://user-images.githubusercontent.com/7306657/143088925-1a5da2fc-1c64-4404-b3e2-6972bcaa11b6.png)

Notes:
For debugging I turned off "dedupe" and verified that in the lowest level (debug) logfile, the logs of the different levels were in the correct order, this is why I think might be a problem with pino-pretty.

**Comment by mcollina** [comment]
This seems the behavior you would get as you have two target streams at different levels pointing to the same destination (stdout).
They will proceed at their own pace and therefore the messages will be interleaved at their destination.

**Comment by frzsombor** [comment]
Thanks for the explanation, I guess then this is not considered as a bug and won't be fixed, so I'm closing this issue.

**Comment by mcollina** [comment]
> Thanks for the explanation, I guess then this is not considered as a bug and won't be fixed, so I'm closing this issue.

I don't think it can be fixed :(.

**Comment by menocomp** [comment]
I can replicate this issue even if I am using one transport and all logs of the same level. The difference here is the logs belong to 2 pino logs names.
See this screenshot.
<img width="202" alt="Screenshot 2024-12-30 at 7 10 05 pm" src="https://github.com/user-attachments/assets/e650cff0-a968-4bfc-9a26-8aefe439bb89" />
