### ISSUE TITLE
question: how to handle messageFormat in webpack typescript environment

### ISSUE THREAD

**Issue by MRisto** [pinojs/pino-pretty#276]
Hi, 
I hope this question is not already explained. Looked through many issues and merge requests.

I want to use the messageFormat in the new pino v7. For that you created a documentation. 

I can't get it to working. It could be due to webpack and typescript. 

I don't know how to set the target. I tried to make it as shown in the documentation. But it does not load the target. 

To be honest i don't understand the syntax. Why is target a string? Is it possible to give a function here directly?

**Comment by mcollina** [comment]
This guide should explain it: https://github.com/pinojs/pino/blob/master/docs/bundling.md
