### ISSUE TITLE
pino-pretty breaks flushing of stdout

### ISSUE THREAD

**Issue by mojavelinux** [pinojs/pino-pretty#279]
pino-pretty overrides the `end` function on the destination to bypass the call to `fs.close`.

```js
if (destination.fd === 1) {
  // We cannot close the output
  destination.end = function () {
    this.emit('close')
  }
}
```

In doing so, it breaks flushing. In other words, if there are messages in the buffer, they get dropped when the function emits the close event.

Since sonic-boom 2.4, the call to `fs.close` is now bypassed, yet the buffer is still flushed. Therefore, I think pino-pretty should remove this logic. Besides, the logic is incomplete anyway as it does not consider stderr.

**Comment by mojavelinux** [comment]
The workaround is to save the end function and reassign it after pino-pretty is initialized:

```js
const end = destination.end
logger = pino(config, createPrettyDestination(destination, colorize))
destination.end = end

```

**Comment by mcollina** [comment]
I agree, this should be removed from pino-pretty. 
Would you like to send a Pull Request to address this issue?

**Comment by mojavelinux** [comment]
Yep! Glad to.

**Comment by mojavelinux** [comment]
Wow, that was a tricky one to write a test for. It took awhile to figure out the minimum code in isolation to trigger the problem. It's pretty clear from the test that SonicBoom is doing the work here, so pino-pretty doesn't need to.

**Comment by mojavelinux** [comment]
Btw, I recognize that calling `end` on the destination isn't the most typical way of using pino. However, it is important when pino is integrated as a framework to build a logger module for an application. The application knows how to create the stream / destination and when it needs to be flushed / closed. It can't rely on the process exit listener to clean things up as that's not when the application stops.
