### ISSUE TITLE
demo.png is broken

### ISSUE THREAD

**Issue by blowsie** [pinojs/pino-pretty#28]
https://github.com/pinojs/pino-pretty/blob/master/demo.png

**Comment by mcollina** [comment]
what do you mean it is broken?
Il giorno mer 29 ago 2018 alle 10:03 Sam Blowes <notifications@github.com>
ha scritto:

**Comment by blowsie** [comment]
Seems to be a CSP issue or something?

![image](https://user-images.githubusercontent.com/308572/44778223-5c6cf280-ab74-11e8-89e2-16c08a5d3eb9.png)

**Comment by mcollina** [comment]
works for me, might be a github bug or something.

**Comment by mcollina** [comment]
<img width="1066" alt="schermata 2018-08-29 alle 11 17 21 1" src="https://user-images.githubusercontent.com/52195/44778399-22ecb500-ab7d-11e8-8495-2ee21507ab34.png">
