### ISSUE TITLE
Using pino-pretty only in development

### ISSUE THREAD

**Issue by marcmarina** [pinojs/pino-pretty#287]
Hello, I'm trying to get pino-pretty to be used only in development. The README mentions adding it as a development dependency. I assumed this would mean it's not used in production, but it tries to use it and it crashes due to the package not being available. What can I do?

What I'm doing now is this:
```js
const logger = pino({
  ...(isDev() ? { transport: { target: 'pino-pretty' } } : {}),
  level: isDev() ? 'trace' : 'info',
});
```

**Comment by mcollina** [comment]
It means `npm i pino-pretty --dev`

**Comment by marcmarina** [comment]
I know, that's clear enough. I'm doing that. The problem is that when deploying since I'm only using production dependencies, it crashes when starting the server because `pino-pretty` is a dev dependency.

**Comment by mcollina** [comment]
Given your code, the only way it could load it is if `isDev()` returns true.

Please upload a full example to reproduce your problem.

**Comment by marcmarina** [comment]
Sorry I should have been clearer. The code I wrote is to work around the issue of it crashing in production. The docs don't mention the fact that you need to set the transporter conditionally.

> We recommend against using pino-pretty in production and highly recommend installing pino-pretty as a development dependency.

And this is the code example.

```js
const pino = require('pino')
const logger = pino({
  transport: {
    target: 'pino-pretty'
  },
})

logger.info('hi')```

**Comment by mcollina** [comment]
You are using pino-pretty if you specify a transport. It's not disabled conditionally for you, so your workaround is exactly how you should integrate it.

**Comment by marcmarina** [comment]
Ah perfect then. I just misunderstood the docs. Thanks!

**Comment by jsumners** [comment]
PRs to improve documentation are always welcome.
