### ISSUE TITLE
Programmatic Integration example fails with node -v 12.13.0 (Not supported)

### ISSUE THREAD

**Issue by ericzon** [pinojs/pino-pretty#291]
Trying the examples taken of: https://github.com/pinojs/pino-pretty#programmatic-integration
using node v14.15.5 works well but using node v12.13.0 appears this error message:

![image](https://user-images.githubusercontent.com/1809508/148347912-6b12f857-78c7-44c9-bca9-f3850e10b614.png)

I don't know if it's a bug or If it's planned to not support node.js v12.x (but is still in Maintenance LTS) I suggest to inform about this in the description of the section.

**Comment by mcollina** [comment]
We only support the latest version of the line. At this time 12.22.7.
