### ISSUE TITLE
Partial Prettyfier

### ISSUE THREAD

**Issue by rubenhak** [pinojs/pino-pretty#31]
Just like available in bunyan and winston, I would like to have ability to prettify the console output only, but keep the output to the file as json. Currently I'm using the following way:

```
const Pino = require('pino');
const multi = require('multi-write-stream');

var logFileStream = fs.createWriteStream('the-path');
var stream = multi([
    process.stdout,
    logFileStream
])

 var pinoOptions = {
    name: this._name,
    prettyPrint: {
        levelFirst: false,
        translateTime: true,
        colorize: true
    },
    prettifier: require('pino-pretty')
}

var logger = Pino(pinoOptions, stream);
```

P.S. I'm aware of the out-of-process prettyfier. In this particular case need to get console prettification in process.

**Comment by mcollina** [comment]
I would recommend to use https://github.com/pinojs/pino-multi-stream instead, as you'll be able prettify in the console and write it to disk using newline-delimited-json for easier processing.
Also, I would highly recommend against using that in production.

We might need to expose https://github.com/pinojs/pino/blob/master/lib/tools.js#L172-L233 to do so. Would you mind to send a PR to pino for it?

**Comment by rubenhak** [comment]
Let me try this and I will get back. Thanks.

**Comment by rubenhak** [comment]
Moved the request to [https://github.com/pinojs/pino/issues/534](https://github.com/pinojs/pino/issues/534)
