### ISSUE TITLE
Cannot set minimumLevel below info

### ISSUE THREAD

**Issue by turkerdev** [pinojs/pino-pretty#313]
Cannot set minimumLevel below info, if i set minimumLevel error, it shows error and higher levels, but setting minimumLevel to debug doesnt show you debug messages.

```json
{
  "levelKey": "level",
  "ignore": "pid,hostname",
  "translateTime": "SYS:HH:MM:ss",
  "minimumLevel": "debug"
}
```

```bash
[16:52:01] FATAL: this is fatal
[16:52:01] ERROR: this is error
[16:52:01] WARN: this is warn
[16:52:01] INFO: this is info
```

**Comment by mcollina** [comment]
This should work as expected, can you include a full example?

**Comment by turkerdev** [comment]
Here is the [repo](https://github.com/turkerdev/pinopretty-temp)

**Comment by mcollina** [comment]
You need to configure pino level to debug or trace.
