### ISSUE TITLE
Same width level display

### ISSUE THREAD

**Issue by BCsabaEngine** [pinojs/pino-pretty#315]
I use pretty and pino with text levels, not numbers. Is there any solution to display the level with same characters, for ex. 3 chars: ERR, WRN, NFO, DBG, etc?

**Comment by jsumners** [comment]
See "custom prettifiers" in https://github.com/pinojs/pino-pretty#options

**Comment by BCsabaEngine** [comment]
Can I use it within command line?

**Comment by jsumners** [comment]
I don't know. I doubt it.
