### ISSUE TITLE
No formatting in Node 14

### ISSUE THREAD

**Issue by jcollum-nutrien** [pinojs/pino-pretty#328]
I looked at the other Node 14 ticket, looks like a different issue. 

This is my output without pino-pretty 

```
✗ node --version
v14.19.1

✗ which pino-pretty
/Users/justin.collum2@nutrien.com/.nvm/versions/node/v14.19.1/bin/pino-pretty

✗ pino-pretty --version
7.6.1

✗ node dist/server.js 
fetching params for redacted; environment = "dev"
{"SeverityText":"INFO","Timestamp":"1649434670392","Resource":{"service.name":"unknown_service","host.name":"Justins-MacBook-Pro.local","process.pid":36967},"Attributes":{"code.filepath":"/Users/redacted/work/redacted/dist/server.js"},"correlationId":"noCorrelationId","sessionId":"noSessionId","userId":"noUserId","userType":"unknownUserType","Body":"Server listening at http://0.0.0.0:10000"}
```

And with pino-pretty: 

```
 ✗ node dist/server.js | pino-pretty
fetching params for redacted; environment = "dev"
    SeverityText: "INFO"
    Timestamp: "1649435307932"
    Resource: {
      "service.name": "unknown_service",
      "host.name": "Justins-MacBook-Pro.local",
      "process.pid": 39935
    }
    Attributes: {
      "code.filepath": "/Users/redacted/work/redacted/dist/server.js"
    }
    correlationId: "noCorrelationId"
    sessionId: "noSessionId"
    userId: "noUserId"
    userType: "unknownUserType"
    Body: "Server listening at http://0.0.0.0:10000"
```

and with some args on pino-pretty: 

```
 ✗ node dist/server.js | pino-pretty -cl
fetching params for redacted; environment = "dev"
    SeverityText: "INFO"
    Timestamp: "1649435344192"
    Resource: {
      "service.name": "unknown_service",
      "host.name": "Justins-MacBook-Pro.local",
      "process.pid": 40012
    }
    Attributes: {
      "code.filepath": "/Users/redacted/work/redacted/dist/server.js"
    }
    correlationId: "noCorrelationId"
    sessionId: "noSessionId"
    userId: "noUserId"
    userType: "unknownUserType"
    Body: "Server listening at http://0.0.0.0:10000"

```

Looks like it's not working.

**Comment by mcollina** [comment]
What's not working?

**Comment by jcollum-nutrien** [comment]
Shouldn't colorize (-c) look like this: https://github.com/pinojs/pino-pretty/raw/master/demo.png ?

**Comment by jsumners** [comment]
What we see is plain text in your report. So we cannot see if coloring has been applied or not.

**Comment by jcollum-nutrien** [comment]
If I post a screenshot it's not going to look any different. There's next to no prettifying happening at all: 

1. no coloring
2. no shortening
3. no readable timestamps 

other than making the JSON more readable it appears that pino-pretty is doing nothing

**Comment by jcollum-nutrien** [comment]
![image](https://user-images.githubusercontent.com/99687439/163221274-49b6ff23-4c14-4a07-aaca-4025e2293c4a.png)

**Comment by jcollum-nutrien** [comment]
![image](https://user-images.githubusercontent.com/99687439/163221472-236e4923-225b-4f37-b5fc-bdd07adaa96c.png)

**Comment by jcollum-nutrien** [comment]
After updating our logger package to have the latest version of Pino and Pino Pretty I'm still not getting color in my output. But if I import Pino directly (cutting out our logger package) I can get colored output. The issue appears to be outside of Pino Pretty. I'll leave this up in case I find some new info that is actionable.

**Comment by jsumners** [comment]
Given that it sounds like a detail in your application, I will close this as not applicable. If you determine otherwise, please reopen it with a minimal reproduction.

**Comment by jcollum-nutrien** [comment]
The root of the issue was that my team was changing the fields output by Pino so instead of `msg` we had `Body`. This broke Pino-Pretty, for obvious reasons. Managed to fix it with `| pino-pretty -cl -t hh:MM:ss TT -i Resource,Attributes,userId,userType,sessionId,correlationId -m Body --levelKey SeverityText -a Timestamp'`

**Comment by jsumners** [comment]
For what it's worth, I do not consider that "breaking" `pino-pretty`. The module did what it is supposed to do: format ndjson into a more legible format.

**Comment by jcollum-nutrien** [comment]
Yeah I don't either. I just didn't notice that the output JSON didn't conform to Pino defaults.
