### ISSUE TITLE
option to turn off prettyprint in api

### ISSUE THREAD

**Issue by rubiin** [pinojs/pino-pretty#329]
Using pretty print along with file in transport. However i cannot seem to turn of pretty printing. Is there anything I am missing

**Comment by mcollina** [comment]
can you make an example?

**Comment by rubiin** [comment]
I am on nestjs using nestjs-pino

Heres how I am logging on std as well as file using transports:
```ts
	
{
                            pinoHttp: {
						level: "info",
						redact: {
							paths: ["req.headers.authorization"],
							remove: true,
						},
						transport: {
							targets: [
								{
									target: "pino/file",
									level: "info",
									options: {
										destination: "logs/info.log",
										mkdir: true,
									},
								},
								{
									target: "pino-pretty",
									level: "info",
									options: {
										colorize: true,
										prettyPrint: false,
										translateTime: true,
										ignore: "pid,hostname",
									},
								},
							],
						},
					},
				};

```

**Comment by rubiin** [comment]
I think pino-pretty does not have a option to turn off prettyPrint at the moment

**Comment by jsumners** [comment]
It doesn't and it won't. If you do not want to pretty print logs, do not send them to the pretty print module.

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.
