### ISSUE TITLE
Cannot handle obj within undefined value

### ISSUE THREAD

**Issue by zyf0330** [pinojs/pino-pretty#33]
When call like this 
```
    log.info({
      app: undefined,
      room: undefined,
    }, 'connect')
```
, it gives error `Cannot read property 'split' of undefined"` at `pino-pretty/index.js:199:27`.
I think pino-pretty should deal with this situation.

**Comment by mcollina** [comment]
I cannot reproduce it. Can you verify you are using the latest version of pino and pino-pretty? If so, can you upload a full example?

**Comment by zyf0330** [comment]
Sorry, I am using v2.0.0. This problem has been fixed now.
