### ISSUE TITLE
pino-pretty not working when running jest test

### ISSUE THREAD

**Issue by jenrrycordero2022** [pinojs/pino-pretty#330]
### Short Description:
I'm trying to build a logger module using Pino. Everything is good until I run our tests cases.

### My code:
```
import pino from 'pino';

const logger = pino({
    transport: {
        level: 'info',
        target: 'pino-pretty',
        options: {
            colorize: true,
            levelFirst: true,
            translateTime: 'SYS:yyyy-mm-dd HH:MM:ss',
            ignore: 'pid,hostname',
        },
    },
});

try {
    // Some functionalities here...
} catch (e) {
        logger.error(`mvpd auth - getPopularMvpds: ${e}`);
}
```

This is the error when running: > `yarn test`

_ReferenceError: setImmediate is not defined_

      at ThreadStream.write (node_modules/thread-stream/index.js:245:7)
      at Pino.write (node_modules/pino/lib/proto.js:208:10)
      at Pino.error (node_modules/pino/lib/tools.js:60:21)

![Screen Shot 2022-04-14 at 3 09 54 PM](https://user-images.githubusercontent.com/97186792/163468755-43d6cc53-42f9-4b88-92db-75a1ee137513.png)

**Comment by mcollina** [comment]
setImmediate is a global defined by Node.js. The fact that's not in your environment is the result of jest configuration.

**Comment by jenrrycordero2022** [comment]
Thanks Matteo!
