### ISSUE TITLE
Doesn't work in browser

### ISSUE THREAD

**Issue by avetisk** [pinojs/pino-pretty#332]
Getting the follow error when using in the browser (with Next.js):

```
error - ./node_modules/pino-pretty/lib/utils.js:7:23
Module not found: Can't resolve 'worker_threads'
```

While `pino({ prettyPrint: { ... })` is deprecated, it still works properly in the browser.

**Comment by jsumners** [comment]
At no point has `pino-pretty` ever been intended to be used in a browser environment.

**Comment by avetisk** [comment]
Then you should mention it in the docs.

Because when you read this in the `pino` docs: 
>Pino is compatible with [browserify](https://npm.im/browserify) for browser side usage:
>This can be useful with isomorphic/universal JavaScript code.

You legitimately think that `pino-pretty` may also be browser friendly.

**Comment by jsumners** [comment]
`pino-pretty` !== `pino`

**Comment by DoisKoh** [comment]
It would be nice for it to be compatible in the browser though. Certain frameworks (specifically thinking of Svelte) requires the code to be isomorphic - Pino's great because it's supported on the browser and allows us to use it everywhere. Pretty-printing it on the browser during development would be great.

**Comment by jsumners** [comment]
`pino-pretty` has never been intended to be used in a production situation. Also, it is specifically designed for reading input from `stdin` and streaming the manipulated data.

**Comment by adrianwix** [comment]
I think @DoisKoh is not asking to use pino-pretty in production but in development. No one wants to read unformatted error logs in development. Also @avetisk has a fair point, he is talking about user expectations. Not about about `pino === pino-pretty`

**Comment by hirako2000** [comment]
I do suggest to mention it on the README. or rename this project pino-nodepretty
Would save many people a little bit of time :)
