### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by qzerrty** [pinojs/pino-pretty#338]
In the Options [section ](https://github.com/pinojs/pino-pretty#options)there is a typo in function for pid
```
    ...
    hostname: hostname => colorGreen(hostname)
    pid: pid => colorRed(hostname) <- typo
    name: name => colorBlue(name)
    caller: caller => colorCyan(caller)
    ...
```
Maybe there should be colorRed(pid)

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
