### ISSUE TITLE
Typings missing `minimumLevel`

### ISSUE THREAD

**Issue by LewisTehMinerz** [pinojs/pino-pretty#339]
`minimumLevel` is a valid option here:
https://github.com/pinojs/pino-pretty/blob/e793e646a0b539b3a9aa8b5ab43e64a8d86b05d6/index.js#L57
But it's not available in the typings:
![](https://discord.coffee/29fkYzN.png)
Which I assume is because it isn't part of the default options set, so when the typings were written it was missed:
https://github.com/pinojs/pino-pretty/blob/e793e646a0b539b3a9aa8b5ab43e64a8d86b05d6/index.js#L30-L48

(psst... what is the default minimum level?)

**Comment by kibertoad** [comment]
Would you be open to send a PR for this? It would also need a tsd test.
