### ISSUE TITLE
NaN and Infinity are logged as null

### ISSUE THREAD

**Issue by nwoltman** [pinojs/pino-pretty#36]
If a value in an object is `NaN` or `Infinity`, it is printed as `null`.

With:

```js
const pino = require('pino')({
  prettyPrint: true,
})

pino.info({
  nan: NaN,
  infinity: Infinity,
})
```

pino prints:

```
[1537734467643] INFO (12908 on my-pc):
    nan: null
    infinity: null
```

With `prettyPrint: false`, pino prints:

```
{"level":30,"time":1537734724883,"pid":10064,"hostname":"my-pc","nan":NaN,"infinity":Infinity,"v":1}
```

Printing `NaN` and `Infinity` might actually be a problem for regular `pino` because `JSON.parse()` can't parse that JSON, however, it would be nice for `pino-pretty` to print `NaN` and `Infinity` because it is hard to debug things when you think the value is `null` but it is actually `NaN`.

It looks like the cause is from using `JSON.stringify()` here:
https://github.com/pinojs/pino-pretty/blob/34414045d2cd7517ad4134d0b766076cd863539b/index.js#L252

**Comment by mcollina** [comment]
I think this is likely a double-bug :/. One in pino (it shouldn't log those as they are not JSON) and pino-pretty (it should log those when used in-process).

**Comment by jsumners** [comment]
Should it? I think regardless of in process or as a pipe it should print the correct information. And that is the JSON data. Given that neither value is valid JSON, it shouldn’t print them.

**Comment by davidmarkclements** [comment]
I agree in principle with James 

But the ability to inspect objects passed to the logger is also useful for debugging 

I think and in-process only fork of pino-pretty - called pino-inspect should provide the dumping of non-JSON values

**Comment by jsumners** [comment]
That’s a decent idea. Or an option, `false` by default, to enable such behavior. But I’m not fond of the maintenance cost for that.

**Comment by mcollina** [comment]
Should be fixed.
