### ISSUE TITLE
Pino pretty puts `name` field into main log line

### ISSUE THREAD

**Issue by paymog** [pinojs/pino-pretty#367]
I have code which looks like the following:

```
      const name = req.params.name;
      const versionLabel = req.params.version_label;
      const childLogger = req.log.child({ name, versionLabel });
      ....
      childLogger.info("deleting dangling webhooks");
      ....
```

and it outputs the following with pino pretty:

```
[api-server] [16:46:06 UTC] INFO (paymahn): deleting dangling webhooks
[api-server]     reqId: "cl6nufc900008dtp20n92391a"
[api-server]     versionLabel: "2"
```

when I would expect it to output something like this:

```
[api-server] [16:46:06 UTC] INFO: deleting dangling webhooks
[api-server]     reqId: "cl6nufc900008dtp20n92391a"
[api-server]     versionLabel: "2"
[api-server]     name: "paymahn"
```

It seems that pino-pretty prints `name` fields in the main log line and not in the log fields as expected. Is there a way to configure pino pretty to print a field called `name` next to all the other fields?

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=name-string

**Comment by paymog** [comment]
ah got it, thanks for pointing me to that! I guess there's no way to disable that?

**Comment by jsumners** [comment]
Don't add the properties to the root merging object. Instead, log a `data` object:

```js
const data = { name: 'foo', answer: 42 }
log.info({ data }, 'some message')
```

You may also look at https://getpino.io/#/docs/api?id=logmethod
