### ISSUE TITLE
Where's my error occur in my project? (How to find exact code line and its file name)

### ISSUE THREAD

**Issue by topninja** [pinojs/pino-pretty#368]
Hello team.
I added logger in many places of my project
And sometimes logger has error logs.

```
const pino = require('pino');
const path = require('path');
const logger = pino({
	prettyPrint: {
		messageFormat: '{filename}: {msg}',
		ignore: 'pid,hostname,filename',
	}
}).child({ filename: __dirname + '\\' + path.basename(__filename) });
```

I did like this so I can see which file, and its error message
![image](https://user-images.githubusercontent.com/47001971/184469791-66324a12-ae3e-4d77-8128-c9ed23764533.png)
But I want to know which line produce this error so I can find issue easily.
How to do this?

Thanks

p.s.
logger.error(new Error('payload is not valid'))
by this, I can get line but shows few more.. I want only 1 line

**Comment by mcollina** [comment]
Remove `messageFormat` and you'll see a full stack trace.

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by topninja** [comment]
I added reproduction example already.
```
const pino = require('pino');
const path = require('path');
const logger = pino({
	prettyPrint: {
		messageFormat: '{filename}: {msg}',
		ignore: 'pid,hostname,filename',
	}
}).child({ filename: __dirname + '\\' + path.basename(__filename) });

logger.error("payload is not valid");
```

**Comment by mcollina** [comment]
You are not creating an error, so there is no stacktrace. If you want to get a stacktrace, create an error.
