### ISSUE TITLE
TS definition index.d.ts and JS index.js are not aligned

### ISSUE THREAD

**Issue by TommyDew42** [pinojs/pino-pretty#369]
From a [discussion](https://github.com/fastify/one-line-logger/pull/1#discussion_r945178625) in a `@fastify/one-line-logger` PR, [index.js](https://github.com/pinojs/pino-pretty/blob/dab76bc39c26f248f79337a728825afa6669ccf6/index.js#L259-L262) and [index.d.ts](https://github.com/pinojs/pino-pretty/blob/dab76bc39c26f248f79337a728825afa6669ccf6/index.d.ts#L154-L162) are not aligned.

Will have a PR if we are confirmed with the issue.

`index.js`:
```js
module.exports = build
module.exports.prettyFactory = prettyFactory
module.exports.colorizerFactory = colors
module.exports.default = build
```

`index.d.ts`:
```ts
declare namespace PinoPretty {
  type Prettifier = (inputData: string | object) => string;
  type MessageFormatFunc = (log: LogDescriptor, messageKey: string, levelLabel: string) => string;
  type PrettyOptions = PrettyOptions_;
  type PrettyStream = Transform & OnUnknown;
}

export default PinoPretty;
export { PinoPretty, PrettyOptions_ as PrettyOptions };
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
