### ISSUE TITLE
`pino.final` does not work with pino-pretty

### ISSUE THREAD

**Issue by eadaniel** [pinojs/pino-pretty#37]
When using `pino.final` with pino-pretty following exception is thrown:

```
only compatible with loggers with pino.destination and pino.extreme targets
```

We are using pretty-printing on the dev boxes and it took me quite a while that `pino.final` works fine without pino-pretty. Below you find code to reproduce the issue.

Best,
Alexander 

```
const pino = require('pino')

const logger = pino({
  prettyPrint: true
})

const run = async () => {
  process.on('SIGTERM', pino.final(logger, (err, finalLogger) => {
    finalLogger.info('Graceful shutdown 1')
    finalLogger.info('Graceful shutdown 2')
    process.exit(0)
  }))

  await delay(30)
}

const delay = (secs) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), secs * 1000)
  })
}

run().catch(err => {
  logger.error({ err })
})
```

**Comment by mcollina** [comment]
This is indeed true. It would be hard to support such a feature.
`prettyPrint: true`  is essentially a _development_ utility, not a production one.
`pino.final` is essentially a _production_ utility, not a development one.
It should be fairly ok to disable one while using the other.

**Comment by jsumners** [comment]
Maybe make `pino.final` a noop when pretty printing is enabled?

**Comment by mcollina** [comment]
Making it a noop won't help - the function will not be fired. We can have `pino.final` be called with the passed-in logger in that case, and we should log another message as warn level: "The destination is not a pino.destination() or pino.extreme() and it does not support synchronous flushing". Would that be better?

**Comment by eadaniel** [comment]
@mcollina That's definitely better.

It would be nice to detect that pino-pretty is used and log a message explaining that `pino.final` can't be used with pino-pretty. At least that would have saved me time finding the root cause.

**Comment by tcoulom** [comment]
would this issue prevent access between AWS and Mainframe environments:

WARN [2025-01-24 17:13:41.856 +0000] (1 on ufwae-ingress-csi-listener-7bc4986f5c-2hggd):
    msg: "pino.final with prettyPrint does not support flushing"
/opt/koa-app/node_modules/kafkajs/src/protocol/error.js:581
  return new KafkaJSProtocolError(errorCodes.find(e => e.code === code) || unknownErrorCode(code))
         ^
KafkaJSProtocolError: Not authorized to access topics: [Topic authorization failed]
