### ISSUE TITLE
additional parameters print?

### ISSUE THREAD

**Issue by shlomich** [pinojs/pino-pretty#388]
Hiya, it seems like pino-pretty is not printing additional parameters, I'm not sure whether this is a pino-pretty thing or pino. but here's the code I am using.

```
import { pino } from 'pino';
import pretty from 'pino-pretty';

const prettyOptions = {
  translateTime: 'yyyy-mm-dd HH:MM:ss',
  // colorize: true,
  sync: true,
  ignore: 'pid,hostname',
};

const stream = pretty(prettyOptions);
export const logger = pino(stream);
logger.level = 'debug';
```

now when I try to do the following:
```
const a = "aaa"
logger.info("printing a", a)
```
// Output: "INFO: printing a"

it doesn't append the parameter itself, any idea what I can do to solve it?

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=logger
