### ISSUE TITLE
How to get EST time using pino-pretty

### ISSUE THREAD

**Issue by SudhirRamaniOD** [pinojs/pino-pretty#406]
I am trying with translateTime: 'EST:DD-MM-YYYY HH:MM:SS' but still getting UTC time only.

**Comment by mcollina** [comment]
THat's not supported by dateformat: https://www.npmjs.com/package/dateformat.
Only `UTC:` prefix is supported.

**Comment by SudhirRamaniOD** [comment]
Is there any way around to get the EST time in pino?

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=pino-stdtimefunctions
