### ISSUE TITLE
--minimumLevel / -L flag doesn't seem to be working

### ISSUE THREAD

**Issue by mysticflute** [pinojs/pino-pretty#410]
I'm using pino-pretty in my project and trying to set the level to `debug` via a cli flag. I have this in my package.json scripts:

```json
"dev": "next dev | pino-pretty -L debug"
```

I've tried `--minimumLevel=debug`, `--minimumLevel debug`, nothing seems to be working.

I've tried other flags such as `-S` and they did work.

**Comment by mysticflute** [comment]
Using `"pino": "^8.11.0"` and `"pino-pretty": "^9.4.0"`

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mysticflute** [comment]
Here's a very basic repo... just a node script that outputs to the logger.:
https://github.com/mysticflute/pino-pretty-test

Try it with `npm test` or or `node index.js | npx pino-pretty -L debug`

**Comment by mcollina** [comment]
You are not setting the log level on the main pino logger, it's not emitting debut level logs.

**Comment by mysticflute** [comment]
Are you saying the `L` flag only operates as a secondary log level, it does not affect the pino log level?

**Comment by mcollina** [comment]
Exactly, they are two separate processes

**Comment by jsumners** [comment]
It is a filter. Note that the help text for that switch indicates so.

**Comment by mysticflute** [comment]
Thanks. In hindsight that does make sense. Using both libraries for the first time, I wasn't thinking about how pino-pretty doesn't directly change any of the behavior of pino.
