### ISSUE TITLE
[Question] Handling non-serializable options in Bundled Package

### ISSUE THREAD

**Issue by victorlrz** [pinojs/pino-pretty#421]
Hello, 

I have a shared package in my monorepo that contains a pino logger file, which is used across several Next.js applications. 
The logger file uses the pino-pretty module to format the logs.

I'm using the new pino v7+ transports, which require non-serializable options. To use messageFormat as a function, I'm trying to wrap pino-pretty as suggested in the documentation.

However, I am struggling to include the pino-pretty-transport file in my shared library and make the custom messageFormat works when I use the exported logger on one of the NextJs App

I am not sure how to proceed with resolving this issue. Could you please provide some guidance on how to include the custom pino-pretty-transport module in my shared library/Next.js builds?

Technical Details: 

`pino-pretty-transport.ts` (shared library)
```
import { LoggerOptions } from 'pino';
import PinoPretty, { PrettyOptions } from 'pino-pretty';

export const pinoPrettyTransport = (opts: PrettyOptions) =>
  PinoPretty({
    ...opts,
    messageFormat: (log: LoggerOptions, messageKey) => {
      const message = log[messageKey] as string;

      return `custom Message ${message}`;
    },
  });
```

`logger.ts` (shared library)
```
export const pinoLogger = pino({
  customLevels: customLevels.levels,
  level: isProduction ? 'info' : 'debug',
  ...(isDev
    ? {
        transport: {
          target: './pino-pretty-transport',
          options: {
            colorize: true,
            customColors: 'warn:yellow,info:green,debug:blue,error:red',
            levelFirst: true,
            ignore: 'service,source,env,time',
          },
        },
      }
    : undefined),
```

Built with tsup (shared library): 

```
export default defineConfig({
  entry: ['src/index.ts'],
  dts: true,
  format: ['esm', 'cjs'],
  clean: true,
  outExtension: ({ format }) => ({
    js: `.${format}.js`,
  }),
});
```

=> 3 files in shared dist folder
```
  "main": "dist/index.cjs.js",
  "module": "dist/index.esm.js",
  "types": "dist/index.d.ts",
```

Then using shared library in one of the NextApp ->   
<img width="944" alt="image" src="https://user-images.githubusercontent.com/60266782/232921878-2ed176a5-c36a-4640-b801-52aafc83c9af.png">

Tried with require.resolve, path.resolve, but not sure how to fix this if you have ideas.
Thanks in advance

**Comment by mcollina** [comment]
Given how workers are setup, you'll need a separate entry point for this and you'd need to use https://github.com/pinojs/pino-webpack-plugin.

**Comment by victorlrz** [comment]
Thanks for your help @mcollina, I'll investigate
