### ISSUE TITLE
Unresponsive logging when using `tail`, `jq` and `pino-pretty`

### ISSUE THREAD

**Issue by samholmes** [pinojs/pino-pretty#424]
```sh
tail -f my.log | jq -Mc 'select(.msg != "some excluded message") | pino-pretty
```

The above command does not appear to be responsive. I have a heartbeat log every 10 seconds, yet the log isn't printed immediately. Instead a bunch of logs are printed after some many minutes in a batch. If I remove `pino-pretty` from the command, the logs are printed immediately. It appears as though `pino-pretty` is buffering logs? I'm using version 10.0.0.

**Comment by jsumners** [comment]
Line 80 of `bin.js` is where the destination stream gets built. That ends up being an `abstract-transport` instance, which if I remember correctly, _will_ default to a buffered `sonic-boom` instance. It would be worthwhile to verify this is correct. If so, a PR to added a CLI switch to disable buffering would be a good solution.

**Comment by samholmes** [comment]
Why would it take so long to empty the buffer though? Even if it were buffered, why is it that the sonic-boom instance hangs for so long?

**Comment by esmiralha** [comment]
any updates on this issue?

**Comment by martijnarts** [comment]
Any workaround for this?
