### ISSUE TITLE
Legitimate data gets interpreted as configuration

### ISSUE THREAD

**Issue by bighappyworld** [pinojs/pino-pretty#44]
I had some logs that printed some business objects (via pino with prettyPrint enabled) that had a `name` field in the object. When it was printed, the field didn't show up.

Instead, it replaced the "pino" name and instead of the proper name showing up, it had the data field value showing up.

When printing an object without the name field:

`[1542282240641] DEBUG (server/11044 on Donut.local)`

When printing an object with the name field:

`[1542282240642] DEBUG (Fred Smith/11044 on Donut.local)`

And then the name field value does NOT show up with the other data from the same object.

As far as what I am passing to the pino call, I'm just passing the raw object.

**Comment by mcollina** [comment]
Thanks for reporting! Can you please include a script to reproduce?

**Comment by bighappyworld** [comment]
```
const pino = require('pino')

const log = pino({
  name: 'service',
  prettyPrint: true,
  level: 'debug'
})

log.debug('Hello')

log.debug({
  a: 'a',
  b: 'b'
})

log.debug({
  name: 'Fred',
  gender: 'male'
})
```

Produces the output of:

```
[1542352040424] DEBUG (service/14800 on Computer.local): Hello
[1542352040426] DEBUG (service/14800 on Computer.local): 
    a: "a"
    b: "b"
[1542352040426] DEBUG (Fred/14800 on Computer.local): 
    gender: "male"
```

So you can see how the "name" attribute of the object being logged gets used as the same "name" attribute from the configuration.

**Comment by mcollina** [comment]
That works exactly as expected. All passed in properties are squashed on the same JSON object. I’d recommend to wrap your properties in another object.

**Comment by bighappyworld** [comment]
The code functions as expected, true. But that doesn't mean it is good behavior.

An object that is being logged should not impact the format of the logger and override previous configuration.

Generally speaking, individual modules should function independent of other modules. It's the same general logic for why you don't modify the prototype of native objects.

All of that being said, I'm not advocating fixing it this moment, but just bringing it up as unexpected behavior when using pino with pretty enabled.
