### ISSUE TITLE
New option to hide level and timestamp at the beginning of a line

### ISSUE THREAD

**Issue by timlohse1104** [pinojs/pino-pretty#444]
In my testing with `--messageFormat` option i came across the question if it would be possible to mirror standard NestJS logs like this:

`[Nest] 45816  - 23.07.2023, 22:09:14     LOG [NestFactory] Starting Nest application... +59ms`

I tried to rebuild it with '--messageFormat' string / function but could not remove the `timestamp`and `level`in the beginning of every log.

I probably overlooked something. But if thats not the case i would like to add another option 'hideMetadata' (name to be discussed). 

I would add logic into https://github.com/pinojs/pino-pretty/blob/master/index.js line 135 and following.

What do you think?

Would also contribute to this closed issue: https://github.com/pinojs/pino-pretty/issues/437

**Comment by timlohse1104** [comment]
Please consider my pr https://github.com/pinojs/pino-pretty/pull/445 .

**Comment by vladshcherbin** [comment]
try

```js
{
  include: ''
}
```

or

```js
{
  ignore: 'level,time'
}
```

**Comment by timlohse1104** [comment]
Thanks @vladshcherbin that's avalid option. No need for a further parameter. This issue can be closed.

**Comment by timlohse1104** [comment]
For anyone interested in a config to recreate NestJS logs see the below .pino-pretty.rc.

{
  "ignore": "pid,hostname,level,time",
  "translateTime": false,
  "singleLine": false,
  "colorize": true,
  "hideObject": true, 
  "messageFormat": "[Nest] {pid}  - {if req.id} ({req.id}) - {end}{time} {level} {if context}[{context}] {end} {msg}"
}
