### ISSUE TITLE
crash on keys that resolve to an undefined value.

### ISSUE THREAD

**Issue by JamesKyburz** [pinojs/pino-pretty#45]
When logging values that resolve to undefined for example functions or objects with overriden toJSON functions pino-pretty crashes in joinLinesWithIndentation when calling split on undefined.

`log.debug({a: { toJSON () {} } })`
TypeError: Cannot read property 'split' of undefined
`log.debug({a: f => f })`
TypeError: Cannot read property 'split' of undefined

I can send a PR to fix?

**Comment by mcollina** [comment]
thanks!

Il giorno mar 20 nov 2018 alle 08:52 James Kyburz <notifications@github.com>
ha scritto:

**Comment by jsumners** [comment]
Yes, please send a PR.
