### ISSUE TITLE
timestamp: false results in empty []

### ISSUE THREAD

**Issue by JasonEtco** [pinojs/pino-pretty#48]
Hiya! I'm trying out `pino(-pretty)` and encountered an unexpected rendering. Here's what I'm seeing in my console:

```
[] INFO  (my-logger): test
```

And here's the code to generate it:

```js
const logger = pino({
  base: { name: my-logger },
  prettyPrint: true,
  timestamp: false
})

logger.info('test')
```

It looks like `timestamp` being set to false is properly omitting it from the log, but the `[<timestamp>]` square brackets are still being printed. As a library user, I would expect the square brackets to also be omitted, and to see this as the output:

```
INFO  (my-logger): test
```

Let me know if I'm doing something weird or if there's anything I can do to help! ✨ 

<details>
<summary>Versions</summary>

```
❯ node -v
v10.13.0

❯ npm list pino pino-pretty
├── pino@5.9.0
└── pino-pretty@2.3.0
```
</details>

**Comment by JasonEtco** [comment]
Judging by this test, it looks like this might be expected behavior:

https://github.com/pinojs/pino-pretty/blob/8101d3bf5b31b05ea608160e56b01b2b44b2c0f1/test/basic.test.js#L273-L284

With that in mind, would y'all be open to a PR that modifies the test (and behavior)?

```diff
-    t.is(formatted, `[undefined] INFO  (${pid} on ${hostname}): hello world\n`)
+    t.is(formatted, `INFO  (${pid} on ${hostname}): hello world\n`)
```

**Comment by jsumners** [comment]
Yep. Go for it.
