### ISSUE TITLE
add badges

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-pretty#5]
travis, code coverage etc..

**Comment by jsumners** [comment]
I added the badges, but I have no idea how to make Coveralls work.

**Comment by mcollina** [comment]
Coveralls is enabled. It's just a matter of configuri tap to upload things to coveralls, see http://www.node-tap.org/coverage/

**Comment by jsumners** [comment]
Weird. I looked at the `pino` repository settings on travis-ci and didn't see any such environment variable set. So I figured it didn't need to be set on this repository.

**Comment by mcollina** [comment]
it's in the secure key in .travis.yml


Il giorno ven 6 apr 2018 alle ore 15:30 James Sumners <
notifications@github.com> ha scritto:

**Comment by jsumners** [comment]
This is resolved.
