### ISSUE TITLE
Time zone does not match

### ISSUE THREAD

**Issue by userVF** [pinojs/pino-pretty#502]
Hi All!

Time zone in log does not match with system one.

+6 in log:
![image](https://github.com/pinojs/pino-pretty/assets/11441427/de17856c-f394-45d9-9f69-4c81282577ea)

+5 in system:
![image](https://github.com/pinojs/pino-pretty/assets/11441427/c2497f99-115b-48df-b807-e1da15c91a16)

js code:
![image](https://github.com/pinojs/pino-pretty/assets/11441427/d9b24c5c-37ae-41ee-beb0-1327c7194db6)

Tested on Fedora 39, AlmaLinux 9, CentOS 8

**Comment by mcollina** [comment]
I have absolutely no clue on why. On my system, things are lined up.
I'm sorry I can't be of help, if you would like to send a PR to fix this, it would be highly welcomed.

(I'd recommend checking what the dateformat library does).

**Comment by userVF** [comment]
Thanks for answer!
I noticed the mismatch happens if `tzdata` is updated after `nodejs` is installed already. Probably, it is not issue of `pino`.
