### ISSUE TITLE
parseFactoryOptions is not a function.

### ISSUE THREAD

**Issue by lynzu** [pinojs/pino-pretty#526]
Im using elysia-logger in bun

#code
const app = new Elysia().use(
  logger({
    transport: {
      target: 'pino-pretty',
      options: {
        colorize: true
      }
    }
  })
);

#error
TypeError: parseFactoryOptions is not a function. (In 'parseFactoryOptions(Object.assign({}, defaultOptions, options))', 'parseFactoryOptions' is undefined)                                                               at prettyFactory (/root/hikari/node_modules/pino-pretty/index.js:113:19)                                                                      at build (/root/hikari/node_modules/pino-pretty/index.js:134:16)       at /root/hikari/node_modules/thread-stream/lib/worker.js:67:23

**Comment by jsumners** [comment]
Thank you for the report. This project targets the [Node.js](https://nodejs.org) runtime. If you are encountering issues using Bun, please file issues there as [requested by them](https://twitter.com/jarredsumner/status/1700497869160268155).
