### ISSUE TITLE
How can I use pino-pretty as an log transformer in a pipeline?

### ISSUE THREAD

**Issue by ccll** [pinojs/pino-pretty#539]
I'd like TO use pino-pretty to convert JSON to human readable, then feed the result to my custom multi-stream.
But it seems that pino-pretty directly output to stdout so my custom stream got nothing.

Am I missing the point of pino's stream based approach?

```ts
  pino(
        {
            transport: {
                pipeline: [
                    {
                        target: "pino-pretty",
                        options: {
                            colorize: true,
                        },
                    },
                ],
            },
        },
        pino.multistream([
            // { stream: process.stdout },
            {
                stream: {
                    write: (msg: string) => {
                        logFunc(msg);
                    },
                },
            },
        ]),
    );
```

**Comment by mcollina** [comment]
Probably. The overall goal is to show pretty logs to humans. multistream is usually for machine processing, therefore trying to machine process something for humans is not really in scope.
