### ISSUE TITLE
Dropping `readable-stream` polyfill

### ISSUE THREAD

**Issue by benmccann** [pinojs/pino-pretty#541]
It looks like the CI tests Node 18.17+, so I guess that might be the minimum version supported by this library. Once that's raised to Node 18.19+ it would be nice to drop the `readable-stream` dependency. I'm guessing that would be a change in supported Node versions and would be considered a breaking change, so might have to wait until the next major.

**Comment by kibertoad** [comment]
Node 18 goes EOL on 2025-04-30, so personally I don't see a big problem with bumping minimum version to Node 20 in the nearby future (in a semver major, of course).
fastify has already done that.

as a bonus, node:test could be used instead of tap then

**Comment by mcollina** [comment]
I'm +1 on removing, send a PR.
