### ISSUE TITLE
Ability to use library without CLI

### ISSUE THREAD

**Issue by benmccann** [pinojs/pino-pretty#544]
Would you accept a PR to refactor this library into a library and a CLI consuming that library? I expect most users only need a library. At least that's true for my own use case.

Quite a lot of the dependencies come from the CLI. E.g. the following are used only in `bin.js`:
- `help-me`
- `pump`
- `joycon`
- `strip-json-comments`
- `minimist`

There may be others that are pulled in by the CLI transitively and not through the library entry points

**Comment by jsumners** [comment]
I don't see a need to do so.
