### ISSUE TITLE
pino-pretty ignores stderr output

### ISSUE THREAD

**Issue by jburghardt** [pinojs/pino-pretty#546]
pino-pretty ignores stderr output.

```node
node -e "process.stdout.write(JSON.stringify(`{'level':50,'time':'2024-11-21T12:42:09.256Z','msg':'test'}`))" | npx pino-pretty
```
-> [13:42:09.256] ERROR: test

```node
node -e "process.stderr.write(JSON.stringify(`{'level':50,'time':'2024-11-21T12:42:09.256Z','msg':'test'}`))" | npx pino-pretty
```
-> {'level':50,'time':'2024-11-21T12:42:09.256Z','msg':'test'}

is this a desired behavior ?

**Comment by jburghardt** [comment]
that is one odd way to say "yes, pino-pretty ignores stderr"

**Comment by jsumners** [comment]
`pino-pretty` works just like any other standard Unix tool that processes input provided via `stdin`. Please do some research on command piping and redirection.
