### ISSUE TITLE
add jq-like functionality to only print some of the rows on a criteria

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-pretty#6]

**Comment by jsumners** [comment]
Why not just provide an example for using `jq`?

**Comment by mcollina** [comment]
That is also possible.

We can easily add something like https://github.com/trentm/node-bunyan/blob/master/bin/bunyan#L230-L238.

**Comment by jsumners** [comment]
https://www.npmjs.com/package/jmespath may be helpful in this endeavor.

**Comment by mcollina** [comment]
I think we should use this, it seems very nice and it’s already implemented.

**Comment by davidmarkclements** [comment]
Looks like a good basis for a general search function .. do we maybe want
to put that into a seperate module that's pino specific

Then other prettifiers could use and have
the same interface (and also anything else
that involves querying logs)

**Comment by jsumners** [comment]
It's up to you guys. I have no interest in implementing this feature. The utilities on my systems are enough for me.
