### ISSUE TITLE
bourne is deprecated

### ISSUE THREAD

**Issue by NAlexandrov** [pinojs/pino-pretty#63]
Hello! I see that you use [bourne](https://www.npmjs.com/package/bourne) in 3.0.0 version. This package is deprecated. Use [@hapi/bourne](https://www.npmjs.com/package/@hapi/bourne) instead.

**Comment by nwoltman** [comment]
@NAlexandrov Why not send a PR? It should be a simple change.

**Comment by NAlexandrov** [comment]
PR #64
