### ISSUE TITLE
Can't use with jest CLI

### ISSUE THREAD

**Issue by trmaphi** [pinojs/pino-pretty#65]
Currently, our set up is
```
     "test": "jest"
```
``` yml
    - yarn test --all --detectOpenHandles | yarn pino-pretty
```
Without pipeline from pino-pretty, jest can be colorized. But, if I add pino-pretty pipeline, it will be just black&while

**Comment by jsumners** [comment]
I have no clue what the output of jest is supposed to be. But I imagine it is detecting that it will not be writing to a regular shell, due to the pipe, and is not even outputting color escape sequences. Even if it did, I doubt you would get the result you desire because `pino-pretty` looks for ndjson as its input.

**Comment by davidmarkclements** [comment]
I think you need to look for an option in jest that says to output color regardless of whether it detect it's in a pipeline or not. If it doesn't have one it's an issue/PR for the Jest team. This is not a problem with pino-pretty

**Comment by trmaphi** [comment]
Thank for recommending. I check `jest` source code, they do use [`chalk` ](https://github.com/facebook/jest/search?q=chalk&unscoped_q=chalk) a lot. It seems like `chalk` config of `jest` will be overridden by your config. I think I might need to convince my team lead, programmatically add logger config ` prettyPrint: { colorize: true }` other environments except for production.

**Comment by jsumners** [comment]
They are separate processes so the config in `pino-pretty` wouldn't have any effect on the config in `jest`. Further, I clearly don't know your environment, but it's generally not common practice to output logs during tests.
