### ISSUE TITLE
cross platform support: windows

### ISSUE THREAD

**Issue by iAbhishek91** [pinojs/pino-pretty#71]
Problem statement: 

I am using PowerShell in windows, and the format of `pino` development is not as expected. This works perfectly in Mac.

**Expected:** [1522431328992] INFO (42 on foo): hello world
**Actual:**  [1522431328992] <-[32mINFO  <-[32m (42 on foo): <-[32m hello world <-[32m

**Comment by jsumners** [comment]
Don't output color?

**Comment by iAbhishek91** [comment]
Yeah, no color is the terminal. `<-[32m` inline character is frustrating.

**Comment by jsumners** [comment]
> Yeah, no color is the terminal. 

I do not understand that statement. Are you running `cat foo.json | pino-pretty -c` or `cat foo.json | pino-pretty`?

**Comment by iAbhishek91** [comment]
I have used the below code:

```javascript
const logger = pino({
  prettyPrint: { colorize: true }
});

logger.info('hello world');
```

The above code prints the below line in powershell.
> [1522431328992] <-[32mINFO <-[32m (42 on foo): <-[32m hello world <-[32m

**Comment by jsumners** [comment]
So as I said, don't output color: `{colorize: false}`.

**Comment by iAbhishek91** [comment]
Sorry for late reply. Thanks for the help.
