### ISSUE TITLE
How would you colorize similarly to console.log?

### ISSUE THREAD

**Issue by SulaimanAlabbar** [pinojs/pino-pretty#79]
Printed two errors to console, once with pino.error and once with console.error. This is my prettyPrint options for pino:

```js
logger = pino({
  prettyPrint: {
    colorize: true,
    translateTime: true,
    errorProps: "*"
  }
});
```
This is console.error:
![consolelog](https://user-images.githubusercontent.com/43919657/64069801-b0645880-cc5a-11e9-8dfd-d28f43f17cb2.png)
And this is pino.error:
![pino](https://user-images.githubusercontent.com/43919657/64069804-b9552a00-cc5a-11e9-8ac7-f2108ea01fac.png)

**Comment by davidmarkclements** [comment]
`console.log` uses `util.inspect`.

If you'd like you could send a PR for say `--inspect-colors` or some such

**Comment by SulaimanAlabbar** [comment]
I don't think it could work with util inspect, since util.inspect needs an object, and you're stringifying objects in logs and handling indentation yourselves. All that would be undone if I turn those strings into objects again and apply colors and indentation.
