### ISSUE TITLE
Log lines with "v":0 is not formatted

### ISSUE THREAD

**Issue by DanielHreben** [pinojs/pino-pretty#80]
Log lines with "v":0 is not formatted:
```bash
$ echo '{"level":30,"msg":"test message","time":1567606368094,"v":0}' | pino-pretty
> {"level":30,"msg":"test message","time":1567606368094,"v":0}
```

Same line with version=1 is formatted as expected:

```bash
$ echo '{"level":30,"msg":"test message","time":1567606368094,"v":1}' | pino-pretty
> [1567606368094] INFO : test message
```

**Comment by mcollina** [comment]
How are you geneating lines with v:0?

I’m good in removing the checks on the v property tbh, would you like to
send a PR?

Il giorno mer 4 set 2019 alle 16:33 Daniel Hreben <notifications@github.com>
ha scritto:

**Comment by DanielHreben** [comment]
Log lines with v:0 generated by bunyan, unfortunately, I can't change it to pino, it is inside 3rd party docker image, but I don't wanna use bunyan cuz it has too much outdated shit in dependencies. 
Sure I don't mind to send pr, but I can't find the place when this check happens, may you point me to this line?

**Comment by jsumners** [comment]
I thought I removed all checks for `v`?

**Comment by DanielHreben** [comment]
🤷‍♂ can't find anything in the codebase, but is should be there, since pino itself is only `devDependency`. Really confused 😕

**Comment by davidmarkclements** [comment]
make sure you're on the latest version

![image](https://user-images.githubusercontent.com/1190716/64275469-e0a34400-cf45-11e9-978a-d377aeeb7cf9.png)

**Comment by DanielHreben** [comment]
Oops. Thanks!
