### ISSUE TITLE
.pino-prettyrc not being honoured

### ISSUE THREAD

**Issue by ruigazio** [pinojs/pino-pretty#94]
https://github.com/pinojs/pino-pretty/blob/c0c6b52ecd58a3844d276ad1a5d8caa263ce0081/bin.js#L72
.pino-prettyrc:
```
{
  "errorProps": "number,cause,status,statusCode,url"
}
```

`console.logs` around referred line (bin.js:72) reveal:

```
before assign {
  config: { errorProps: 'number,cause,status,statusCode,url' },
  opts: {
    e: '',
    errorProps: '',
    k: 'err,error',
    errorLikeObjectKeys: 'err,error'
  }
}
after assign {
  config: { errorProps: 'number,cause,status,statusCode,url' },
  opts: {
    errorProps: '',
    e: '',
    k: 'err,error',
    errorLikeObjectKeys: 'err,error'
  }
}
```

**Comment by mcollina** [comment]
I don't really understand this. Can you please provide clearer instructions on how to reproduce?

**Comment by rui-atg** [comment]
`pino-pretty -e "number,cause,status,statusCode,url"` behaves as expected.
Using just `pino-pretty` and setting the option above in `.pino-prettyrc` instead, does not work as expected.
