### ISSUE TITLE
Windows color

### ISSUE THREAD

**Issue by quetzalsly** [pinojs/pino-pretty#96]
Colorize option does not work on windows and the only choice is to disable it. However on Winston logger I had basic color output just fine. How is that possible? and can we somehow copy whatever Winston is doing to make it work?

**Comment by mcollina** [comment]
It _should_ work, so this is likely a bug. Would you like to send a PR?

**Comment by Fdawgs** [comment]
Unable to replicate this issue using the following:

OS: Windows 10 Home 20H2
Node.js: v14.15.5
pino-pretty: v4.5.0


![Capture](https://user-images.githubusercontent.com/43814140/108514845-4b704880-72bc-11eb-87b7-9bf9737288d9.PNG)

**Comment by JakubKoralewski** [comment]
I had this when pino-pretty was inside the npm script, i.e. "dev": "next | npx pino-pretty", but doing "npm run dev | npx pino-pretty" instead fixed it, idk if it's the same problem or I somehow misunderstand how shells work but the end result is that there were no colors, maybe that could help in repro? but again not sure if the same issue
